// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: olap_file.proto

package com.starrocks.proto;

public interface AlterTabletPBOrBuilder extends
    // @@protoc_insertion_point(interface_extends:starrocks.AlterTabletPB)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .starrocks.AlterTabletState alter_state = 1;</code>
   * @return Whether the alterState field is set.
   */
  boolean hasAlterState();
  /**
   * <code>optional .starrocks.AlterTabletState alter_state = 1;</code>
   * @return The alterState.
   */
  com.starrocks.proto.AlterTabletState getAlterState();

  /**
   * <code>required int64 related_tablet_id = 2;</code>
   * @return Whether the relatedTabletId field is set.
   */
  boolean hasRelatedTabletId();
  /**
   * <code>required int64 related_tablet_id = 2;</code>
   * @return The relatedTabletId.
   */
  long getRelatedTabletId();

  /**
   * <code>optional int32 related_schema_hash = 3;</code>
   * @return Whether the relatedSchemaHash field is set.
   */
  boolean hasRelatedSchemaHash();
  /**
   * <code>optional int32 related_schema_hash = 3;</code>
   * @return The relatedSchemaHash.
   */
  int getRelatedSchemaHash();

  /**
   * <code>optional .starrocks.AlterTabletType alter_type = 4;</code>
   * @return Whether the alterType field is set.
   */
  boolean hasAlterType();
  /**
   * <code>optional .starrocks.AlterTabletType alter_type = 4;</code>
   * @return The alterType.
   */
  com.starrocks.proto.AlterTabletType getAlterType();
}
