// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: olap_file.proto

package io.datafibre.fibre.proto;

public interface OLAPRawDeltaHeaderMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:starrocks.OLAPRawDeltaHeaderMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int32 schema_hash = 2;</code>
   * @return Whether the schemaHash field is set.
   */
  boolean hasSchemaHash();
  /**
   * <code>required int32 schema_hash = 2;</code>
   * @return The schemaHash.
   */
  int getSchemaHash();
}
