// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internal_service.proto

package com.starrocks.proto;

public interface PExecShortCircuitRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:starrocks.PExecShortCircuitRequest)
    com.google.protobuf.MessageOrBuilder {
}
