// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internal_service.proto

package com.starrocks.proto;

public interface PFetchDataRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:starrocks.PFetchDataRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required .starrocks.PUniqueId finst_id = 1;</code>
   * @return Whether the finstId field is set.
   */
  boolean hasFinstId();
  /**
   * <code>required .starrocks.PUniqueId finst_id = 1;</code>
   * @return The finstId.
   */
  com.starrocks.proto.PUniqueId getFinstId();
  /**
   * <code>required .starrocks.PUniqueId finst_id = 1;</code>
   */
  com.starrocks.proto.PUniqueIdOrBuilder getFinstIdOrBuilder();
}
