// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internal_service.proto

package io.datafibre.fibre.proto;

public interface PPulsarBacklogBatchProxyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:starrocks.PPulsarBacklogBatchProxyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .starrocks.PPulsarBacklogProxyRequest requests = 1;</code>
   */
  java.util.List<io.datafibre.fibre.proto.PPulsarBacklogProxyRequest>
      getRequestsList();
  /**
   * <code>repeated .starrocks.PPulsarBacklogProxyRequest requests = 1;</code>
   */
  io.datafibre.fibre.proto.PPulsarBacklogProxyRequest getRequests(int index);
  /**
   * <code>repeated .starrocks.PPulsarBacklogProxyRequest requests = 1;</code>
   */
  int getRequestsCount();
  /**
   * <code>repeated .starrocks.PPulsarBacklogProxyRequest requests = 1;</code>
   */
  java.util.List<? extends io.datafibre.fibre.proto.PPulsarBacklogProxyRequestOrBuilder>
      getRequestsOrBuilderList();
  /**
   * <code>repeated .starrocks.PPulsarBacklogProxyRequest requests = 1;</code>
   */
  io.datafibre.fibre.proto.PPulsarBacklogProxyRequestOrBuilder getRequestsOrBuilder(
      int index);
}
