// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internal_service.proto

package io.datafibre.fibre.proto;

public interface PTabletWriterAddSegmentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:starrocks.PTabletWriterAddSegmentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .starrocks.PUniqueId id = 1;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>optional .starrocks.PUniqueId id = 1;</code>
   * @return The id.
   */
  io.datafibre.fibre.proto.PUniqueId getId();
  /**
   * <code>optional .starrocks.PUniqueId id = 1;</code>
   */
  io.datafibre.fibre.proto.PUniqueIdOrBuilder getIdOrBuilder();

  /**
   * <code>optional int64 index_id = 2;</code>
   * @return Whether the indexId field is set.
   */
  boolean hasIndexId();
  /**
   * <code>optional int64 index_id = 2;</code>
   * @return The indexId.
   */
  long getIndexId();

  /**
   * <code>optional int64 tablet_id = 3;</code>
   * @return Whether the tabletId field is set.
   */
  boolean hasTabletId();
  /**
   * <code>optional int64 tablet_id = 3;</code>
   * @return The tabletId.
   */
  long getTabletId();

  /**
   * <code>optional int64 txn_id = 4;</code>
   * @return Whether the txnId field is set.
   */
  boolean hasTxnId();
  /**
   * <code>optional int64 txn_id = 4;</code>
   * @return The txnId.
   */
  long getTxnId();

  /**
   * <code>optional bool eos = 5;</code>
   * @return Whether the eos field is set.
   */
  boolean hasEos();
  /**
   * <code>optional bool eos = 5;</code>
   * @return The eos.
   */
  boolean getEos();

  /**
   * <code>optional int64 num_segments = 6;</code>
   * @return Whether the numSegments field is set.
   */
  boolean hasNumSegments();
  /**
   * <code>optional int64 num_segments = 6;</code>
   * @return The numSegments.
   */
  long getNumSegments();

  /**
   * <code>optional .starrocks.SegmentPB segment = 7;</code>
   * @return Whether the segment field is set.
   */
  boolean hasSegment();
  /**
   * <code>optional .starrocks.SegmentPB segment = 7;</code>
   * @return The segment.
   */
  io.datafibre.fibre.proto.SegmentPB getSegment();
  /**
   * <code>optional .starrocks.SegmentPB segment = 7;</code>
   */
  io.datafibre.fibre.proto.SegmentPBOrBuilder getSegmentOrBuilder();
}
