// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internal_service.proto

package com.starrocks.proto;

/**
 * Protobuf type {@code starrocks.PTabletWriterOpenResult}
 */
public final class PTabletWriterOpenResult extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:starrocks.PTabletWriterOpenResult)
    PTabletWriterOpenResultOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PTabletWriterOpenResult.newBuilder() to construct.
  private PTabletWriterOpenResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PTabletWriterOpenResult() {
    immutableTabletIds_ = emptyLongList();
    immutablePartitionIds_ = emptyLongList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PTabletWriterOpenResult();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.starrocks.proto.InternalService.internal_static_starrocks_PTabletWriterOpenResult_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.starrocks.proto.InternalService.internal_static_starrocks_PTabletWriterOpenResult_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.starrocks.proto.PTabletWriterOpenResult.class, com.starrocks.proto.PTabletWriterOpenResult.Builder.class);
  }

  private int bitField0_;
  public static final int STATUS_FIELD_NUMBER = 1;
  private com.starrocks.proto.StatusPB status_;
  /**
   * <code>required .starrocks.StatusPB status = 1;</code>
   * @return Whether the status field is set.
   */
  @java.lang.Override
  public boolean hasStatus() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required .starrocks.StatusPB status = 1;</code>
   * @return The status.
   */
  @java.lang.Override
  public com.starrocks.proto.StatusPB getStatus() {
    return status_ == null ? com.starrocks.proto.StatusPB.getDefaultInstance() : status_;
  }
  /**
   * <code>required .starrocks.StatusPB status = 1;</code>
   */
  @java.lang.Override
  public com.starrocks.proto.StatusPBOrBuilder getStatusOrBuilder() {
    return status_ == null ? com.starrocks.proto.StatusPB.getDefaultInstance() : status_;
  }

  public static final int IS_REPEATED_CHUNK_FIELD_NUMBER = 2;
  private boolean isRepeatedChunk_;
  /**
   * <code>optional bool is_repeated_chunk = 2 [default = false];</code>
   * @return Whether the isRepeatedChunk field is set.
   */
  @java.lang.Override
  public boolean hasIsRepeatedChunk() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional bool is_repeated_chunk = 2 [default = false];</code>
   * @return The isRepeatedChunk.
   */
  @java.lang.Override
  public boolean getIsRepeatedChunk() {
    return isRepeatedChunk_;
  }

  public static final int IMMUTABLE_TABLET_IDS_FIELD_NUMBER = 3;
  private com.google.protobuf.Internal.LongList immutableTabletIds_;
  /**
   * <code>repeated int64 immutable_tablet_ids = 3;</code>
   * @return A list containing the immutableTabletIds.
   */
  @java.lang.Override
  public java.util.List<java.lang.Long>
      getImmutableTabletIdsList() {
    return immutableTabletIds_;
  }
  /**
   * <code>repeated int64 immutable_tablet_ids = 3;</code>
   * @return The count of immutableTabletIds.
   */
  public int getImmutableTabletIdsCount() {
    return immutableTabletIds_.size();
  }
  /**
   * <code>repeated int64 immutable_tablet_ids = 3;</code>
   * @param index The index of the element to return.
   * @return The immutableTabletIds at the given index.
   */
  public long getImmutableTabletIds(int index) {
    return immutableTabletIds_.getLong(index);
  }

  public static final int IMMUTABLE_PARTITION_IDS_FIELD_NUMBER = 4;
  private com.google.protobuf.Internal.LongList immutablePartitionIds_;
  /**
   * <code>repeated int64 immutable_partition_ids = 4;</code>
   * @return A list containing the immutablePartitionIds.
   */
  @java.lang.Override
  public java.util.List<java.lang.Long>
      getImmutablePartitionIdsList() {
    return immutablePartitionIds_;
  }
  /**
   * <code>repeated int64 immutable_partition_ids = 4;</code>
   * @return The count of immutablePartitionIds.
   */
  public int getImmutablePartitionIdsCount() {
    return immutablePartitionIds_.size();
  }
  /**
   * <code>repeated int64 immutable_partition_ids = 4;</code>
   * @param index The index of the element to return.
   * @return The immutablePartitionIds at the given index.
   */
  public long getImmutablePartitionIds(int index) {
    return immutablePartitionIds_.getLong(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasStatus()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!getStatus().isInitialized()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getStatus());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeBool(2, isRepeatedChunk_);
    }
    for (int i = 0; i < immutableTabletIds_.size(); i++) {
      output.writeInt64(3, immutableTabletIds_.getLong(i));
    }
    for (int i = 0; i < immutablePartitionIds_.size(); i++) {
      output.writeInt64(4, immutablePartitionIds_.getLong(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getStatus());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, isRepeatedChunk_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < immutableTabletIds_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt64SizeNoTag(immutableTabletIds_.getLong(i));
      }
      size += dataSize;
      size += 1 * getImmutableTabletIdsList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < immutablePartitionIds_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt64SizeNoTag(immutablePartitionIds_.getLong(i));
      }
      size += dataSize;
      size += 1 * getImmutablePartitionIdsList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.starrocks.proto.PTabletWriterOpenResult)) {
      return super.equals(obj);
    }
    com.starrocks.proto.PTabletWriterOpenResult other = (com.starrocks.proto.PTabletWriterOpenResult) obj;

    if (hasStatus() != other.hasStatus()) return false;
    if (hasStatus()) {
      if (!getStatus()
          .equals(other.getStatus())) return false;
    }
    if (hasIsRepeatedChunk() != other.hasIsRepeatedChunk()) return false;
    if (hasIsRepeatedChunk()) {
      if (getIsRepeatedChunk()
          != other.getIsRepeatedChunk()) return false;
    }
    if (!getImmutableTabletIdsList()
        .equals(other.getImmutableTabletIdsList())) return false;
    if (!getImmutablePartitionIdsList()
        .equals(other.getImmutablePartitionIdsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasStatus()) {
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus().hashCode();
    }
    if (hasIsRepeatedChunk()) {
      hash = (37 * hash) + IS_REPEATED_CHUNK_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsRepeatedChunk());
    }
    if (getImmutableTabletIdsCount() > 0) {
      hash = (37 * hash) + IMMUTABLE_TABLET_IDS_FIELD_NUMBER;
      hash = (53 * hash) + getImmutableTabletIdsList().hashCode();
    }
    if (getImmutablePartitionIdsCount() > 0) {
      hash = (37 * hash) + IMMUTABLE_PARTITION_IDS_FIELD_NUMBER;
      hash = (53 * hash) + getImmutablePartitionIdsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.starrocks.proto.PTabletWriterOpenResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.starrocks.proto.PTabletWriterOpenResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.starrocks.proto.PTabletWriterOpenResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.starrocks.proto.PTabletWriterOpenResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.starrocks.proto.PTabletWriterOpenResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.starrocks.proto.PTabletWriterOpenResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.starrocks.proto.PTabletWriterOpenResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.starrocks.proto.PTabletWriterOpenResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.starrocks.proto.PTabletWriterOpenResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.starrocks.proto.PTabletWriterOpenResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.starrocks.proto.PTabletWriterOpenResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.starrocks.proto.PTabletWriterOpenResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.starrocks.proto.PTabletWriterOpenResult prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code starrocks.PTabletWriterOpenResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:starrocks.PTabletWriterOpenResult)
      com.starrocks.proto.PTabletWriterOpenResultOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.starrocks.proto.InternalService.internal_static_starrocks_PTabletWriterOpenResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.starrocks.proto.InternalService.internal_static_starrocks_PTabletWriterOpenResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.starrocks.proto.PTabletWriterOpenResult.class, com.starrocks.proto.PTabletWriterOpenResult.Builder.class);
    }

    // Construct using com.starrocks.proto.PTabletWriterOpenResult.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getStatusFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (statusBuilder_ == null) {
        status_ = null;
      } else {
        statusBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      isRepeatedChunk_ = false;
      bitField0_ = (bitField0_ & ~0x00000002);
      immutableTabletIds_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000004);
      immutablePartitionIds_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.starrocks.proto.InternalService.internal_static_starrocks_PTabletWriterOpenResult_descriptor;
    }

    @java.lang.Override
    public com.starrocks.proto.PTabletWriterOpenResult getDefaultInstanceForType() {
      return com.starrocks.proto.PTabletWriterOpenResult.getDefaultInstance();
    }

    @java.lang.Override
    public com.starrocks.proto.PTabletWriterOpenResult build() {
      com.starrocks.proto.PTabletWriterOpenResult result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.starrocks.proto.PTabletWriterOpenResult buildPartial() {
      com.starrocks.proto.PTabletWriterOpenResult result = new com.starrocks.proto.PTabletWriterOpenResult(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        if (statusBuilder_ == null) {
          result.status_ = status_;
        } else {
          result.status_ = statusBuilder_.build();
        }
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.isRepeatedChunk_ = isRepeatedChunk_;
        to_bitField0_ |= 0x00000002;
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        immutableTabletIds_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000004);
      }
      result.immutableTabletIds_ = immutableTabletIds_;
      if (((bitField0_ & 0x00000008) != 0)) {
        immutablePartitionIds_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000008);
      }
      result.immutablePartitionIds_ = immutablePartitionIds_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.starrocks.proto.PTabletWriterOpenResult) {
        return mergeFrom((com.starrocks.proto.PTabletWriterOpenResult)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.starrocks.proto.PTabletWriterOpenResult other) {
      if (other == com.starrocks.proto.PTabletWriterOpenResult.getDefaultInstance()) return this;
      if (other.hasStatus()) {
        mergeStatus(other.getStatus());
      }
      if (other.hasIsRepeatedChunk()) {
        setIsRepeatedChunk(other.getIsRepeatedChunk());
      }
      if (!other.immutableTabletIds_.isEmpty()) {
        if (immutableTabletIds_.isEmpty()) {
          immutableTabletIds_ = other.immutableTabletIds_;
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ensureImmutableTabletIdsIsMutable();
          immutableTabletIds_.addAll(other.immutableTabletIds_);
        }
        onChanged();
      }
      if (!other.immutablePartitionIds_.isEmpty()) {
        if (immutablePartitionIds_.isEmpty()) {
          immutablePartitionIds_ = other.immutablePartitionIds_;
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          ensureImmutablePartitionIdsIsMutable();
          immutablePartitionIds_.addAll(other.immutablePartitionIds_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      if (!hasStatus()) {
        return false;
      }
      if (!getStatus().isInitialized()) {
        return false;
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getStatusFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              isRepeatedChunk_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              long v = input.readInt64();
              ensureImmutableTabletIdsIsMutable();
              immutableTabletIds_.addLong(v);
              break;
            } // case 24
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureImmutableTabletIdsIsMutable();
              while (input.getBytesUntilLimit() > 0) {
                immutableTabletIds_.addLong(input.readInt64());
              }
              input.popLimit(limit);
              break;
            } // case 26
            case 32: {
              long v = input.readInt64();
              ensureImmutablePartitionIdsIsMutable();
              immutablePartitionIds_.addLong(v);
              break;
            } // case 32
            case 34: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureImmutablePartitionIdsIsMutable();
              while (input.getBytesUntilLimit() > 0) {
                immutablePartitionIds_.addLong(input.readInt64());
              }
              input.popLimit(limit);
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.starrocks.proto.StatusPB status_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.starrocks.proto.StatusPB, com.starrocks.proto.StatusPB.Builder, com.starrocks.proto.StatusPBOrBuilder> statusBuilder_;
    /**
     * <code>required .starrocks.StatusPB status = 1;</code>
     * @return Whether the status field is set.
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required .starrocks.StatusPB status = 1;</code>
     * @return The status.
     */
    public com.starrocks.proto.StatusPB getStatus() {
      if (statusBuilder_ == null) {
        return status_ == null ? com.starrocks.proto.StatusPB.getDefaultInstance() : status_;
      } else {
        return statusBuilder_.getMessage();
      }
    }
    /**
     * <code>required .starrocks.StatusPB status = 1;</code>
     */
    public Builder setStatus(com.starrocks.proto.StatusPB value) {
      if (statusBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        status_ = value;
        onChanged();
      } else {
        statusBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>required .starrocks.StatusPB status = 1;</code>
     */
    public Builder setStatus(
        com.starrocks.proto.StatusPB.Builder builderForValue) {
      if (statusBuilder_ == null) {
        status_ = builderForValue.build();
        onChanged();
      } else {
        statusBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>required .starrocks.StatusPB status = 1;</code>
     */
    public Builder mergeStatus(com.starrocks.proto.StatusPB value) {
      if (statusBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
            status_ != null &&
            status_ != com.starrocks.proto.StatusPB.getDefaultInstance()) {
          status_ =
            com.starrocks.proto.StatusPB.newBuilder(status_).mergeFrom(value).buildPartial();
        } else {
          status_ = value;
        }
        onChanged();
      } else {
        statusBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <code>required .starrocks.StatusPB status = 1;</code>
     */
    public Builder clearStatus() {
      if (statusBuilder_ == null) {
        status_ = null;
        onChanged();
      } else {
        statusBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }
    /**
     * <code>required .starrocks.StatusPB status = 1;</code>
     */
    public com.starrocks.proto.StatusPB.Builder getStatusBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getStatusFieldBuilder().getBuilder();
    }
    /**
     * <code>required .starrocks.StatusPB status = 1;</code>
     */
    public com.starrocks.proto.StatusPBOrBuilder getStatusOrBuilder() {
      if (statusBuilder_ != null) {
        return statusBuilder_.getMessageOrBuilder();
      } else {
        return status_ == null ?
            com.starrocks.proto.StatusPB.getDefaultInstance() : status_;
      }
    }
    /**
     * <code>required .starrocks.StatusPB status = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.starrocks.proto.StatusPB, com.starrocks.proto.StatusPB.Builder, com.starrocks.proto.StatusPBOrBuilder> 
        getStatusFieldBuilder() {
      if (statusBuilder_ == null) {
        statusBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.starrocks.proto.StatusPB, com.starrocks.proto.StatusPB.Builder, com.starrocks.proto.StatusPBOrBuilder>(
                getStatus(),
                getParentForChildren(),
                isClean());
        status_ = null;
      }
      return statusBuilder_;
    }

    private boolean isRepeatedChunk_ ;
    /**
     * <code>optional bool is_repeated_chunk = 2 [default = false];</code>
     * @return Whether the isRepeatedChunk field is set.
     */
    @java.lang.Override
    public boolean hasIsRepeatedChunk() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional bool is_repeated_chunk = 2 [default = false];</code>
     * @return The isRepeatedChunk.
     */
    @java.lang.Override
    public boolean getIsRepeatedChunk() {
      return isRepeatedChunk_;
    }
    /**
     * <code>optional bool is_repeated_chunk = 2 [default = false];</code>
     * @param value The isRepeatedChunk to set.
     * @return This builder for chaining.
     */
    public Builder setIsRepeatedChunk(boolean value) {
      bitField0_ |= 0x00000002;
      isRepeatedChunk_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool is_repeated_chunk = 2 [default = false];</code>
     * @return This builder for chaining.
     */
    public Builder clearIsRepeatedChunk() {
      bitField0_ = (bitField0_ & ~0x00000002);
      isRepeatedChunk_ = false;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.LongList immutableTabletIds_ = emptyLongList();
    private void ensureImmutableTabletIdsIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        immutableTabletIds_ = mutableCopy(immutableTabletIds_);
        bitField0_ |= 0x00000004;
       }
    }
    /**
     * <code>repeated int64 immutable_tablet_ids = 3;</code>
     * @return A list containing the immutableTabletIds.
     */
    public java.util.List<java.lang.Long>
        getImmutableTabletIdsList() {
      return ((bitField0_ & 0x00000004) != 0) ?
               java.util.Collections.unmodifiableList(immutableTabletIds_) : immutableTabletIds_;
    }
    /**
     * <code>repeated int64 immutable_tablet_ids = 3;</code>
     * @return The count of immutableTabletIds.
     */
    public int getImmutableTabletIdsCount() {
      return immutableTabletIds_.size();
    }
    /**
     * <code>repeated int64 immutable_tablet_ids = 3;</code>
     * @param index The index of the element to return.
     * @return The immutableTabletIds at the given index.
     */
    public long getImmutableTabletIds(int index) {
      return immutableTabletIds_.getLong(index);
    }
    /**
     * <code>repeated int64 immutable_tablet_ids = 3;</code>
     * @param index The index to set the value at.
     * @param value The immutableTabletIds to set.
     * @return This builder for chaining.
     */
    public Builder setImmutableTabletIds(
        int index, long value) {
      ensureImmutableTabletIdsIsMutable();
      immutableTabletIds_.setLong(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 immutable_tablet_ids = 3;</code>
     * @param value The immutableTabletIds to add.
     * @return This builder for chaining.
     */
    public Builder addImmutableTabletIds(long value) {
      ensureImmutableTabletIdsIsMutable();
      immutableTabletIds_.addLong(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 immutable_tablet_ids = 3;</code>
     * @param values The immutableTabletIds to add.
     * @return This builder for chaining.
     */
    public Builder addAllImmutableTabletIds(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureImmutableTabletIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, immutableTabletIds_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 immutable_tablet_ids = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearImmutableTabletIds() {
      immutableTabletIds_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.LongList immutablePartitionIds_ = emptyLongList();
    private void ensureImmutablePartitionIdsIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        immutablePartitionIds_ = mutableCopy(immutablePartitionIds_);
        bitField0_ |= 0x00000008;
       }
    }
    /**
     * <code>repeated int64 immutable_partition_ids = 4;</code>
     * @return A list containing the immutablePartitionIds.
     */
    public java.util.List<java.lang.Long>
        getImmutablePartitionIdsList() {
      return ((bitField0_ & 0x00000008) != 0) ?
               java.util.Collections.unmodifiableList(immutablePartitionIds_) : immutablePartitionIds_;
    }
    /**
     * <code>repeated int64 immutable_partition_ids = 4;</code>
     * @return The count of immutablePartitionIds.
     */
    public int getImmutablePartitionIdsCount() {
      return immutablePartitionIds_.size();
    }
    /**
     * <code>repeated int64 immutable_partition_ids = 4;</code>
     * @param index The index of the element to return.
     * @return The immutablePartitionIds at the given index.
     */
    public long getImmutablePartitionIds(int index) {
      return immutablePartitionIds_.getLong(index);
    }
    /**
     * <code>repeated int64 immutable_partition_ids = 4;</code>
     * @param index The index to set the value at.
     * @param value The immutablePartitionIds to set.
     * @return This builder for chaining.
     */
    public Builder setImmutablePartitionIds(
        int index, long value) {
      ensureImmutablePartitionIdsIsMutable();
      immutablePartitionIds_.setLong(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 immutable_partition_ids = 4;</code>
     * @param value The immutablePartitionIds to add.
     * @return This builder for chaining.
     */
    public Builder addImmutablePartitionIds(long value) {
      ensureImmutablePartitionIdsIsMutable();
      immutablePartitionIds_.addLong(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 immutable_partition_ids = 4;</code>
     * @param values The immutablePartitionIds to add.
     * @return This builder for chaining.
     */
    public Builder addAllImmutablePartitionIds(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureImmutablePartitionIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, immutablePartitionIds_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 immutable_partition_ids = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearImmutablePartitionIds() {
      immutablePartitionIds_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:starrocks.PTabletWriterOpenResult)
  }

  // @@protoc_insertion_point(class_scope:starrocks.PTabletWriterOpenResult)
  private static final com.starrocks.proto.PTabletWriterOpenResult DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.starrocks.proto.PTabletWriterOpenResult();
  }

  public static com.starrocks.proto.PTabletWriterOpenResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<PTabletWriterOpenResult>
      PARSER = new com.google.protobuf.AbstractParser<PTabletWriterOpenResult>() {
    @java.lang.Override
    public PTabletWriterOpenResult parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PTabletWriterOpenResult> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PTabletWriterOpenResult> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.starrocks.proto.PTabletWriterOpenResult getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

