// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: internal_service.proto

package io.datafibre.fibre.proto;

/**
 * <pre>
 * if this runtime filter is partial
 * if it's partial, then it's supposed to be merged.
 * otherwise it's supported to be consumed.
 * </pre>
 *
 * Protobuf type {@code starrocks.PTransmitRuntimeFilterParams}
 */
public final class PTransmitRuntimeFilterParams extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:starrocks.PTransmitRuntimeFilterParams)
    PTransmitRuntimeFilterParamsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PTransmitRuntimeFilterParams.newBuilder() to construct.
  private PTransmitRuntimeFilterParams(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PTransmitRuntimeFilterParams() {
    data_ = com.google.protobuf.ByteString.EMPTY;
    probeFinstIds_ = java.util.Collections.emptyList();
    forwardTargets_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PTransmitRuntimeFilterParams();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.datafibre.fibre.proto.InternalService.internal_static_starrocks_PTransmitRuntimeFilterParams_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.datafibre.fibre.proto.InternalService.internal_static_starrocks_PTransmitRuntimeFilterParams_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.datafibre.fibre.proto.PTransmitRuntimeFilterParams.class, io.datafibre.fibre.proto.PTransmitRuntimeFilterParams.Builder.class);
  }

  private int bitField0_;
  public static final int IS_PARTIAL_FIELD_NUMBER = 1;
  private boolean isPartial_;
  /**
   * <code>optional bool is_partial = 1;</code>
   * @return Whether the isPartial field is set.
   */
  @java.lang.Override
  public boolean hasIsPartial() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional bool is_partial = 1;</code>
   * @return The isPartial.
   */
  @java.lang.Override
  public boolean getIsPartial() {
    return isPartial_;
  }

  public static final int QUERY_ID_FIELD_NUMBER = 3;
  private io.datafibre.fibre.proto.PUniqueId queryId_;
  /**
   * <code>optional .starrocks.PUniqueId query_id = 3;</code>
   * @return Whether the queryId field is set.
   */
  @java.lang.Override
  public boolean hasQueryId() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional .starrocks.PUniqueId query_id = 3;</code>
   * @return The queryId.
   */
  @java.lang.Override
  public io.datafibre.fibre.proto.PUniqueId getQueryId() {
    return queryId_ == null ? io.datafibre.fibre.proto.PUniqueId.getDefaultInstance() : queryId_;
  }
  /**
   * <code>optional .starrocks.PUniqueId query_id = 3;</code>
   */
  @java.lang.Override
  public io.datafibre.fibre.proto.PUniqueIdOrBuilder getQueryIdOrBuilder() {
    return queryId_ == null ? io.datafibre.fibre.proto.PUniqueId.getDefaultInstance() : queryId_;
  }

  public static final int FILTER_ID_FIELD_NUMBER = 4;
  private int filterId_;
  /**
   * <code>optional int32 filter_id = 4;</code>
   * @return Whether the filterId field is set.
   */
  @java.lang.Override
  public boolean hasFilterId() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional int32 filter_id = 4;</code>
   * @return The filterId.
   */
  @java.lang.Override
  public int getFilterId() {
    return filterId_;
  }

  public static final int FINST_ID_FIELD_NUMBER = 5;
  private io.datafibre.fibre.proto.PUniqueId finstId_;
  /**
   * <code>optional .starrocks.PUniqueId finst_id = 5;</code>
   * @return Whether the finstId field is set.
   */
  @java.lang.Override
  public boolean hasFinstId() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional .starrocks.PUniqueId finst_id = 5;</code>
   * @return The finstId.
   */
  @java.lang.Override
  public io.datafibre.fibre.proto.PUniqueId getFinstId() {
    return finstId_ == null ? io.datafibre.fibre.proto.PUniqueId.getDefaultInstance() : finstId_;
  }
  /**
   * <code>optional .starrocks.PUniqueId finst_id = 5;</code>
   */
  @java.lang.Override
  public io.datafibre.fibre.proto.PUniqueIdOrBuilder getFinstIdOrBuilder() {
    return finstId_ == null ? io.datafibre.fibre.proto.PUniqueId.getDefaultInstance() : finstId_;
  }

  public static final int DATA_FIELD_NUMBER = 6;
  private com.google.protobuf.ByteString data_;
  /**
   * <code>optional bytes data = 6;</code>
   * @return Whether the data field is set.
   */
  @java.lang.Override
  public boolean hasData() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional bytes data = 6;</code>
   * @return The data.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getData() {
    return data_;
  }

  public static final int PROBE_FINST_IDS_FIELD_NUMBER = 7;
  private java.util.List<io.datafibre.fibre.proto.PUniqueId> probeFinstIds_;
  /**
   * <pre>
   * Multiple probe fragment instances maybe on a single host.
   * </pre>
   *
   * <code>repeated .starrocks.PUniqueId probe_finst_ids = 7;</code>
   */
  @java.lang.Override
  public java.util.List<io.datafibre.fibre.proto.PUniqueId> getProbeFinstIdsList() {
    return probeFinstIds_;
  }
  /**
   * <pre>
   * Multiple probe fragment instances maybe on a single host.
   * </pre>
   *
   * <code>repeated .starrocks.PUniqueId probe_finst_ids = 7;</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.datafibre.fibre.proto.PUniqueIdOrBuilder>
      getProbeFinstIdsOrBuilderList() {
    return probeFinstIds_;
  }
  /**
   * <pre>
   * Multiple probe fragment instances maybe on a single host.
   * </pre>
   *
   * <code>repeated .starrocks.PUniqueId probe_finst_ids = 7;</code>
   */
  @java.lang.Override
  public int getProbeFinstIdsCount() {
    return probeFinstIds_.size();
  }
  /**
   * <pre>
   * Multiple probe fragment instances maybe on a single host.
   * </pre>
   *
   * <code>repeated .starrocks.PUniqueId probe_finst_ids = 7;</code>
   */
  @java.lang.Override
  public io.datafibre.fibre.proto.PUniqueId getProbeFinstIds(int index) {
    return probeFinstIds_.get(index);
  }
  /**
   * <pre>
   * Multiple probe fragment instances maybe on a single host.
   * </pre>
   *
   * <code>repeated .starrocks.PUniqueId probe_finst_ids = 7;</code>
   */
  @java.lang.Override
  public io.datafibre.fibre.proto.PUniqueIdOrBuilder getProbeFinstIdsOrBuilder(
      int index) {
    return probeFinstIds_.get(index);
  }

  public static final int BUILD_BE_NUMBER_FIELD_NUMBER = 8;
  private int buildBeNumber_;
  /**
   * <code>optional int32 build_be_number = 8;</code>
   * @return Whether the buildBeNumber field is set.
   */
  @java.lang.Override
  public boolean hasBuildBeNumber() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>optional int32 build_be_number = 8;</code>
   * @return The buildBeNumber.
   */
  @java.lang.Override
  public int getBuildBeNumber() {
    return buildBeNumber_;
  }

  public static final int FORWARD_TARGETS_FIELD_NUMBER = 9;
  private java.util.List<io.datafibre.fibre.proto.PTransmitRuntimeFilterForwardTarget> forwardTargets_;
  /**
   * <code>repeated .starrocks.PTransmitRuntimeFilterForwardTarget forward_targets = 9;</code>
   */
  @java.lang.Override
  public java.util.List<io.datafibre.fibre.proto.PTransmitRuntimeFilterForwardTarget> getForwardTargetsList() {
    return forwardTargets_;
  }
  /**
   * <code>repeated .starrocks.PTransmitRuntimeFilterForwardTarget forward_targets = 9;</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.datafibre.fibre.proto.PTransmitRuntimeFilterForwardTargetOrBuilder>
      getForwardTargetsOrBuilderList() {
    return forwardTargets_;
  }
  /**
   * <code>repeated .starrocks.PTransmitRuntimeFilterForwardTarget forward_targets = 9;</code>
   */
  @java.lang.Override
  public int getForwardTargetsCount() {
    return forwardTargets_.size();
  }
  /**
   * <code>repeated .starrocks.PTransmitRuntimeFilterForwardTarget forward_targets = 9;</code>
   */
  @java.lang.Override
  public io.datafibre.fibre.proto.PTransmitRuntimeFilterForwardTarget getForwardTargets(int index) {
    return forwardTargets_.get(index);
  }
  /**
   * <code>repeated .starrocks.PTransmitRuntimeFilterForwardTarget forward_targets = 9;</code>
   */
  @java.lang.Override
  public io.datafibre.fibre.proto.PTransmitRuntimeFilterForwardTargetOrBuilder getForwardTargetsOrBuilder(
      int index) {
    return forwardTargets_.get(index);
  }

  public static final int BROADCAST_TIMESTAMP_FIELD_NUMBER = 10;
  private long broadcastTimestamp_;
  /**
   * <pre>
   * When merge node starts to broadcast this rf(millseconds since unix epoch).
   * </pre>
   *
   * <code>optional int64 broadcast_timestamp = 10;</code>
   * @return Whether the broadcastTimestamp field is set.
   */
  @java.lang.Override
  public boolean hasBroadcastTimestamp() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <pre>
   * When merge node starts to broadcast this rf(millseconds since unix epoch).
   * </pre>
   *
   * <code>optional int64 broadcast_timestamp = 10;</code>
   * @return The broadcastTimestamp.
   */
  @java.lang.Override
  public long getBroadcastTimestamp() {
    return broadcastTimestamp_;
  }

  public static final int IS_PIPELINE_FIELD_NUMBER = 11;
  private boolean isPipeline_;
  /**
   * <code>optional bool is_pipeline = 11;</code>
   * @return Whether the isPipeline field is set.
   */
  @java.lang.Override
  public boolean hasIsPipeline() {
    return ((bitField0_ & 0x00000080) != 0);
  }
  /**
   * <code>optional bool is_pipeline = 11;</code>
   * @return The isPipeline.
   */
  @java.lang.Override
  public boolean getIsPipeline() {
    return isPipeline_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (hasQueryId()) {
      if (!getQueryId().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    if (hasFinstId()) {
      if (!getFinstId().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    for (int i = 0; i < getProbeFinstIdsCount(); i++) {
      if (!getProbeFinstIds(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    for (int i = 0; i < getForwardTargetsCount(); i++) {
      if (!getForwardTargets(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeBool(1, isPartial_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(3, getQueryId());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeInt32(4, filterId_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeMessage(5, getFinstId());
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeBytes(6, data_);
    }
    for (int i = 0; i < probeFinstIds_.size(); i++) {
      output.writeMessage(7, probeFinstIds_.get(i));
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      output.writeInt32(8, buildBeNumber_);
    }
    for (int i = 0; i < forwardTargets_.size(); i++) {
      output.writeMessage(9, forwardTargets_.get(i));
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      output.writeInt64(10, broadcastTimestamp_);
    }
    if (((bitField0_ & 0x00000080) != 0)) {
      output.writeBool(11, isPipeline_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, isPartial_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getQueryId());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, filterId_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getFinstId());
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(6, data_);
    }
    for (int i = 0; i < probeFinstIds_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, probeFinstIds_.get(i));
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, buildBeNumber_);
    }
    for (int i = 0; i < forwardTargets_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, forwardTargets_.get(i));
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(10, broadcastTimestamp_);
    }
    if (((bitField0_ & 0x00000080) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(11, isPipeline_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.datafibre.fibre.proto.PTransmitRuntimeFilterParams)) {
      return super.equals(obj);
    }
    io.datafibre.fibre.proto.PTransmitRuntimeFilterParams other = (io.datafibre.fibre.proto.PTransmitRuntimeFilterParams) obj;

    if (hasIsPartial() != other.hasIsPartial()) return false;
    if (hasIsPartial()) {
      if (getIsPartial()
          != other.getIsPartial()) return false;
    }
    if (hasQueryId() != other.hasQueryId()) return false;
    if (hasQueryId()) {
      if (!getQueryId()
          .equals(other.getQueryId())) return false;
    }
    if (hasFilterId() != other.hasFilterId()) return false;
    if (hasFilterId()) {
      if (getFilterId()
          != other.getFilterId()) return false;
    }
    if (hasFinstId() != other.hasFinstId()) return false;
    if (hasFinstId()) {
      if (!getFinstId()
          .equals(other.getFinstId())) return false;
    }
    if (hasData() != other.hasData()) return false;
    if (hasData()) {
      if (!getData()
          .equals(other.getData())) return false;
    }
    if (!getProbeFinstIdsList()
        .equals(other.getProbeFinstIdsList())) return false;
    if (hasBuildBeNumber() != other.hasBuildBeNumber()) return false;
    if (hasBuildBeNumber()) {
      if (getBuildBeNumber()
          != other.getBuildBeNumber()) return false;
    }
    if (!getForwardTargetsList()
        .equals(other.getForwardTargetsList())) return false;
    if (hasBroadcastTimestamp() != other.hasBroadcastTimestamp()) return false;
    if (hasBroadcastTimestamp()) {
      if (getBroadcastTimestamp()
          != other.getBroadcastTimestamp()) return false;
    }
    if (hasIsPipeline() != other.hasIsPipeline()) return false;
    if (hasIsPipeline()) {
      if (getIsPipeline()
          != other.getIsPipeline()) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasIsPartial()) {
      hash = (37 * hash) + IS_PARTIAL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsPartial());
    }
    if (hasQueryId()) {
      hash = (37 * hash) + QUERY_ID_FIELD_NUMBER;
      hash = (53 * hash) + getQueryId().hashCode();
    }
    if (hasFilterId()) {
      hash = (37 * hash) + FILTER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getFilterId();
    }
    if (hasFinstId()) {
      hash = (37 * hash) + FINST_ID_FIELD_NUMBER;
      hash = (53 * hash) + getFinstId().hashCode();
    }
    if (hasData()) {
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
    }
    if (getProbeFinstIdsCount() > 0) {
      hash = (37 * hash) + PROBE_FINST_IDS_FIELD_NUMBER;
      hash = (53 * hash) + getProbeFinstIdsList().hashCode();
    }
    if (hasBuildBeNumber()) {
      hash = (37 * hash) + BUILD_BE_NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getBuildBeNumber();
    }
    if (getForwardTargetsCount() > 0) {
      hash = (37 * hash) + FORWARD_TARGETS_FIELD_NUMBER;
      hash = (53 * hash) + getForwardTargetsList().hashCode();
    }
    if (hasBroadcastTimestamp()) {
      hash = (37 * hash) + BROADCAST_TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getBroadcastTimestamp());
    }
    if (hasIsPipeline()) {
      hash = (37 * hash) + IS_PIPELINE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsPipeline());
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.datafibre.fibre.proto.PTransmitRuntimeFilterParams parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.datafibre.fibre.proto.PTransmitRuntimeFilterParams parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.datafibre.fibre.proto.PTransmitRuntimeFilterParams parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.datafibre.fibre.proto.PTransmitRuntimeFilterParams parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.datafibre.fibre.proto.PTransmitRuntimeFilterParams parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.datafibre.fibre.proto.PTransmitRuntimeFilterParams parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.datafibre.fibre.proto.PTransmitRuntimeFilterParams parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.datafibre.fibre.proto.PTransmitRuntimeFilterParams parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.datafibre.fibre.proto.PTransmitRuntimeFilterParams parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.datafibre.fibre.proto.PTransmitRuntimeFilterParams parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.datafibre.fibre.proto.PTransmitRuntimeFilterParams parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.datafibre.fibre.proto.PTransmitRuntimeFilterParams parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.datafibre.fibre.proto.PTransmitRuntimeFilterParams prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * if this runtime filter is partial
   * if it's partial, then it's supposed to be merged.
   * otherwise it's supported to be consumed.
   * </pre>
   *
   * Protobuf type {@code starrocks.PTransmitRuntimeFilterParams}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:starrocks.PTransmitRuntimeFilterParams)
      io.datafibre.fibre.proto.PTransmitRuntimeFilterParamsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.datafibre.fibre.proto.InternalService.internal_static_starrocks_PTransmitRuntimeFilterParams_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.datafibre.fibre.proto.InternalService.internal_static_starrocks_PTransmitRuntimeFilterParams_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.datafibre.fibre.proto.PTransmitRuntimeFilterParams.class, io.datafibre.fibre.proto.PTransmitRuntimeFilterParams.Builder.class);
    }

    // Construct using io.datafibre.fibre.proto.PTransmitRuntimeFilterParams.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getQueryIdFieldBuilder();
        getFinstIdFieldBuilder();
        getProbeFinstIdsFieldBuilder();
        getForwardTargetsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      isPartial_ = false;
      bitField0_ = (bitField0_ & ~0x00000001);
      if (queryIdBuilder_ == null) {
        queryId_ = null;
      } else {
        queryIdBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      filterId_ = 0;
      bitField0_ = (bitField0_ & ~0x00000004);
      if (finstIdBuilder_ == null) {
        finstId_ = null;
      } else {
        finstIdBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      data_ = com.google.protobuf.ByteString.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000010);
      if (probeFinstIdsBuilder_ == null) {
        probeFinstIds_ = java.util.Collections.emptyList();
      } else {
        probeFinstIds_ = null;
        probeFinstIdsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000020);
      buildBeNumber_ = 0;
      bitField0_ = (bitField0_ & ~0x00000040);
      if (forwardTargetsBuilder_ == null) {
        forwardTargets_ = java.util.Collections.emptyList();
      } else {
        forwardTargets_ = null;
        forwardTargetsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000080);
      broadcastTimestamp_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000100);
      isPipeline_ = false;
      bitField0_ = (bitField0_ & ~0x00000200);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.datafibre.fibre.proto.InternalService.internal_static_starrocks_PTransmitRuntimeFilterParams_descriptor;
    }

    @java.lang.Override
    public io.datafibre.fibre.proto.PTransmitRuntimeFilterParams getDefaultInstanceForType() {
      return io.datafibre.fibre.proto.PTransmitRuntimeFilterParams.getDefaultInstance();
    }

    @java.lang.Override
    public io.datafibre.fibre.proto.PTransmitRuntimeFilterParams build() {
      io.datafibre.fibre.proto.PTransmitRuntimeFilterParams result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.datafibre.fibre.proto.PTransmitRuntimeFilterParams buildPartial() {
      io.datafibre.fibre.proto.PTransmitRuntimeFilterParams result = new io.datafibre.fibre.proto.PTransmitRuntimeFilterParams(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.isPartial_ = isPartial_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        if (queryIdBuilder_ == null) {
          result.queryId_ = queryId_;
        } else {
          result.queryId_ = queryIdBuilder_.build();
        }
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.filterId_ = filterId_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        if (finstIdBuilder_ == null) {
          result.finstId_ = finstId_;
        } else {
          result.finstId_ = finstIdBuilder_.build();
        }
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        to_bitField0_ |= 0x00000010;
      }
      result.data_ = data_;
      if (probeFinstIdsBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0)) {
          probeFinstIds_ = java.util.Collections.unmodifiableList(probeFinstIds_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.probeFinstIds_ = probeFinstIds_;
      } else {
        result.probeFinstIds_ = probeFinstIdsBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.buildBeNumber_ = buildBeNumber_;
        to_bitField0_ |= 0x00000020;
      }
      if (forwardTargetsBuilder_ == null) {
        if (((bitField0_ & 0x00000080) != 0)) {
          forwardTargets_ = java.util.Collections.unmodifiableList(forwardTargets_);
          bitField0_ = (bitField0_ & ~0x00000080);
        }
        result.forwardTargets_ = forwardTargets_;
      } else {
        result.forwardTargets_ = forwardTargetsBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.broadcastTimestamp_ = broadcastTimestamp_;
        to_bitField0_ |= 0x00000040;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.isPipeline_ = isPipeline_;
        to_bitField0_ |= 0x00000080;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.datafibre.fibre.proto.PTransmitRuntimeFilterParams) {
        return mergeFrom((io.datafibre.fibre.proto.PTransmitRuntimeFilterParams)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.datafibre.fibre.proto.PTransmitRuntimeFilterParams other) {
      if (other == io.datafibre.fibre.proto.PTransmitRuntimeFilterParams.getDefaultInstance()) return this;
      if (other.hasIsPartial()) {
        setIsPartial(other.getIsPartial());
      }
      if (other.hasQueryId()) {
        mergeQueryId(other.getQueryId());
      }
      if (other.hasFilterId()) {
        setFilterId(other.getFilterId());
      }
      if (other.hasFinstId()) {
        mergeFinstId(other.getFinstId());
      }
      if (other.hasData()) {
        setData(other.getData());
      }
      if (probeFinstIdsBuilder_ == null) {
        if (!other.probeFinstIds_.isEmpty()) {
          if (probeFinstIds_.isEmpty()) {
            probeFinstIds_ = other.probeFinstIds_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureProbeFinstIdsIsMutable();
            probeFinstIds_.addAll(other.probeFinstIds_);
          }
          onChanged();
        }
      } else {
        if (!other.probeFinstIds_.isEmpty()) {
          if (probeFinstIdsBuilder_.isEmpty()) {
            probeFinstIdsBuilder_.dispose();
            probeFinstIdsBuilder_ = null;
            probeFinstIds_ = other.probeFinstIds_;
            bitField0_ = (bitField0_ & ~0x00000020);
            probeFinstIdsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getProbeFinstIdsFieldBuilder() : null;
          } else {
            probeFinstIdsBuilder_.addAllMessages(other.probeFinstIds_);
          }
        }
      }
      if (other.hasBuildBeNumber()) {
        setBuildBeNumber(other.getBuildBeNumber());
      }
      if (forwardTargetsBuilder_ == null) {
        if (!other.forwardTargets_.isEmpty()) {
          if (forwardTargets_.isEmpty()) {
            forwardTargets_ = other.forwardTargets_;
            bitField0_ = (bitField0_ & ~0x00000080);
          } else {
            ensureForwardTargetsIsMutable();
            forwardTargets_.addAll(other.forwardTargets_);
          }
          onChanged();
        }
      } else {
        if (!other.forwardTargets_.isEmpty()) {
          if (forwardTargetsBuilder_.isEmpty()) {
            forwardTargetsBuilder_.dispose();
            forwardTargetsBuilder_ = null;
            forwardTargets_ = other.forwardTargets_;
            bitField0_ = (bitField0_ & ~0x00000080);
            forwardTargetsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getForwardTargetsFieldBuilder() : null;
          } else {
            forwardTargetsBuilder_.addAllMessages(other.forwardTargets_);
          }
        }
      }
      if (other.hasBroadcastTimestamp()) {
        setBroadcastTimestamp(other.getBroadcastTimestamp());
      }
      if (other.hasIsPipeline()) {
        setIsPipeline(other.getIsPipeline());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      if (hasQueryId()) {
        if (!getQueryId().isInitialized()) {
          return false;
        }
      }
      if (hasFinstId()) {
        if (!getFinstId().isInitialized()) {
          return false;
        }
      }
      for (int i = 0; i < getProbeFinstIdsCount(); i++) {
        if (!getProbeFinstIds(i).isInitialized()) {
          return false;
        }
      }
      for (int i = 0; i < getForwardTargetsCount(); i++) {
        if (!getForwardTargets(i).isInitialized()) {
          return false;
        }
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              isPartial_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 26: {
              input.readMessage(
                  getQueryIdFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 26
            case 32: {
              filterId_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 32
            case 42: {
              input.readMessage(
                  getFinstIdFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 42
            case 50: {
              data_ = input.readBytes();
              bitField0_ |= 0x00000010;
              break;
            } // case 50
            case 58: {
              io.datafibre.fibre.proto.PUniqueId m =
                  input.readMessage(
                      io.datafibre.fibre.proto.PUniqueId.PARSER,
                      extensionRegistry);
              if (probeFinstIdsBuilder_ == null) {
                ensureProbeFinstIdsIsMutable();
                probeFinstIds_.add(m);
              } else {
                probeFinstIdsBuilder_.addMessage(m);
              }
              break;
            } // case 58
            case 64: {
              buildBeNumber_ = input.readInt32();
              bitField0_ |= 0x00000040;
              break;
            } // case 64
            case 74: {
              io.datafibre.fibre.proto.PTransmitRuntimeFilterForwardTarget m =
                  input.readMessage(
                      io.datafibre.fibre.proto.PTransmitRuntimeFilterForwardTarget.PARSER,
                      extensionRegistry);
              if (forwardTargetsBuilder_ == null) {
                ensureForwardTargetsIsMutable();
                forwardTargets_.add(m);
              } else {
                forwardTargetsBuilder_.addMessage(m);
              }
              break;
            } // case 74
            case 80: {
              broadcastTimestamp_ = input.readInt64();
              bitField0_ |= 0x00000100;
              break;
            } // case 80
            case 88: {
              isPipeline_ = input.readBool();
              bitField0_ |= 0x00000200;
              break;
            } // case 88
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean isPartial_ ;
    /**
     * <code>optional bool is_partial = 1;</code>
     * @return Whether the isPartial field is set.
     */
    @java.lang.Override
    public boolean hasIsPartial() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional bool is_partial = 1;</code>
     * @return The isPartial.
     */
    @java.lang.Override
    public boolean getIsPartial() {
      return isPartial_;
    }
    /**
     * <code>optional bool is_partial = 1;</code>
     * @param value The isPartial to set.
     * @return This builder for chaining.
     */
    public Builder setIsPartial(boolean value) {
      bitField0_ |= 0x00000001;
      isPartial_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool is_partial = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsPartial() {
      bitField0_ = (bitField0_ & ~0x00000001);
      isPartial_ = false;
      onChanged();
      return this;
    }

    private io.datafibre.fibre.proto.PUniqueId queryId_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.datafibre.fibre.proto.PUniqueId, io.datafibre.fibre.proto.PUniqueId.Builder, io.datafibre.fibre.proto.PUniqueIdOrBuilder> queryIdBuilder_;
    /**
     * <code>optional .starrocks.PUniqueId query_id = 3;</code>
     * @return Whether the queryId field is set.
     */
    public boolean hasQueryId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .starrocks.PUniqueId query_id = 3;</code>
     * @return The queryId.
     */
    public io.datafibre.fibre.proto.PUniqueId getQueryId() {
      if (queryIdBuilder_ == null) {
        return queryId_ == null ? io.datafibre.fibre.proto.PUniqueId.getDefaultInstance() : queryId_;
      } else {
        return queryIdBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .starrocks.PUniqueId query_id = 3;</code>
     */
    public Builder setQueryId(io.datafibre.fibre.proto.PUniqueId value) {
      if (queryIdBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        queryId_ = value;
        onChanged();
      } else {
        queryIdBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>optional .starrocks.PUniqueId query_id = 3;</code>
     */
    public Builder setQueryId(
        io.datafibre.fibre.proto.PUniqueId.Builder builderForValue) {
      if (queryIdBuilder_ == null) {
        queryId_ = builderForValue.build();
        onChanged();
      } else {
        queryIdBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>optional .starrocks.PUniqueId query_id = 3;</code>
     */
    public Builder mergeQueryId(io.datafibre.fibre.proto.PUniqueId value) {
      if (queryIdBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
            queryId_ != null &&
            queryId_ != io.datafibre.fibre.proto.PUniqueId.getDefaultInstance()) {
          queryId_ =
            io.datafibre.fibre.proto.PUniqueId.newBuilder(queryId_).mergeFrom(value).buildPartial();
        } else {
          queryId_ = value;
        }
        onChanged();
      } else {
        queryIdBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>optional .starrocks.PUniqueId query_id = 3;</code>
     */
    public Builder clearQueryId() {
      if (queryIdBuilder_ == null) {
        queryId_ = null;
        onChanged();
      } else {
        queryIdBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }
    /**
     * <code>optional .starrocks.PUniqueId query_id = 3;</code>
     */
    public io.datafibre.fibre.proto.PUniqueId.Builder getQueryIdBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getQueryIdFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .starrocks.PUniqueId query_id = 3;</code>
     */
    public io.datafibre.fibre.proto.PUniqueIdOrBuilder getQueryIdOrBuilder() {
      if (queryIdBuilder_ != null) {
        return queryIdBuilder_.getMessageOrBuilder();
      } else {
        return queryId_ == null ?
            io.datafibre.fibre.proto.PUniqueId.getDefaultInstance() : queryId_;
      }
    }
    /**
     * <code>optional .starrocks.PUniqueId query_id = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.datafibre.fibre.proto.PUniqueId, io.datafibre.fibre.proto.PUniqueId.Builder, io.datafibre.fibre.proto.PUniqueIdOrBuilder>
        getQueryIdFieldBuilder() {
      if (queryIdBuilder_ == null) {
        queryIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.datafibre.fibre.proto.PUniqueId, io.datafibre.fibre.proto.PUniqueId.Builder, io.datafibre.fibre.proto.PUniqueIdOrBuilder>(
                getQueryId(),
                getParentForChildren(),
                isClean());
        queryId_ = null;
      }
      return queryIdBuilder_;
    }

    private int filterId_ ;
    /**
     * <code>optional int32 filter_id = 4;</code>
     * @return Whether the filterId field is set.
     */
    @java.lang.Override
    public boolean hasFilterId() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int32 filter_id = 4;</code>
     * @return The filterId.
     */
    @java.lang.Override
    public int getFilterId() {
      return filterId_;
    }
    /**
     * <code>optional int32 filter_id = 4;</code>
     * @param value The filterId to set.
     * @return This builder for chaining.
     */
    public Builder setFilterId(int value) {
      bitField0_ |= 0x00000004;
      filterId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 filter_id = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearFilterId() {
      bitField0_ = (bitField0_ & ~0x00000004);
      filterId_ = 0;
      onChanged();
      return this;
    }

    private io.datafibre.fibre.proto.PUniqueId finstId_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.datafibre.fibre.proto.PUniqueId, io.datafibre.fibre.proto.PUniqueId.Builder, io.datafibre.fibre.proto.PUniqueIdOrBuilder> finstIdBuilder_;
    /**
     * <code>optional .starrocks.PUniqueId finst_id = 5;</code>
     * @return Whether the finstId field is set.
     */
    public boolean hasFinstId() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional .starrocks.PUniqueId finst_id = 5;</code>
     * @return The finstId.
     */
    public io.datafibre.fibre.proto.PUniqueId getFinstId() {
      if (finstIdBuilder_ == null) {
        return finstId_ == null ? io.datafibre.fibre.proto.PUniqueId.getDefaultInstance() : finstId_;
      } else {
        return finstIdBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .starrocks.PUniqueId finst_id = 5;</code>
     */
    public Builder setFinstId(io.datafibre.fibre.proto.PUniqueId value) {
      if (finstIdBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        finstId_ = value;
        onChanged();
      } else {
        finstIdBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      return this;
    }
    /**
     * <code>optional .starrocks.PUniqueId finst_id = 5;</code>
     */
    public Builder setFinstId(
        io.datafibre.fibre.proto.PUniqueId.Builder builderForValue) {
      if (finstIdBuilder_ == null) {
        finstId_ = builderForValue.build();
        onChanged();
      } else {
        finstIdBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      return this;
    }
    /**
     * <code>optional .starrocks.PUniqueId finst_id = 5;</code>
     */
    public Builder mergeFinstId(io.datafibre.fibre.proto.PUniqueId value) {
      if (finstIdBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
            finstId_ != null &&
            finstId_ != io.datafibre.fibre.proto.PUniqueId.getDefaultInstance()) {
          finstId_ =
            io.datafibre.fibre.proto.PUniqueId.newBuilder(finstId_).mergeFrom(value).buildPartial();
        } else {
          finstId_ = value;
        }
        onChanged();
      } else {
        finstIdBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000008;
      return this;
    }
    /**
     * <code>optional .starrocks.PUniqueId finst_id = 5;</code>
     */
    public Builder clearFinstId() {
      if (finstIdBuilder_ == null) {
        finstId_ = null;
        onChanged();
      } else {
        finstIdBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }
    /**
     * <code>optional .starrocks.PUniqueId finst_id = 5;</code>
     */
    public io.datafibre.fibre.proto.PUniqueId.Builder getFinstIdBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getFinstIdFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .starrocks.PUniqueId finst_id = 5;</code>
     */
    public io.datafibre.fibre.proto.PUniqueIdOrBuilder getFinstIdOrBuilder() {
      if (finstIdBuilder_ != null) {
        return finstIdBuilder_.getMessageOrBuilder();
      } else {
        return finstId_ == null ?
            io.datafibre.fibre.proto.PUniqueId.getDefaultInstance() : finstId_;
      }
    }
    /**
     * <code>optional .starrocks.PUniqueId finst_id = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.datafibre.fibre.proto.PUniqueId, io.datafibre.fibre.proto.PUniqueId.Builder, io.datafibre.fibre.proto.PUniqueIdOrBuilder>
        getFinstIdFieldBuilder() {
      if (finstIdBuilder_ == null) {
        finstIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.datafibre.fibre.proto.PUniqueId, io.datafibre.fibre.proto.PUniqueId.Builder, io.datafibre.fibre.proto.PUniqueIdOrBuilder>(
                getFinstId(),
                getParentForChildren(),
                isClean());
        finstId_ = null;
      }
      return finstIdBuilder_;
    }

    private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes data = 6;</code>
     * @return Whether the data field is set.
     */
    @java.lang.Override
    public boolean hasData() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional bytes data = 6;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }
    /**
     * <code>optional bytes data = 6;</code>
     * @param value The data to set.
     * @return This builder for chaining.
     */
    public Builder setData(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      data_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bytes data = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearData() {
      bitField0_ = (bitField0_ & ~0x00000010);
      data_ = getDefaultInstance().getData();
      onChanged();
      return this;
    }

    private java.util.List<io.datafibre.fibre.proto.PUniqueId> probeFinstIds_ =
      java.util.Collections.emptyList();
    private void ensureProbeFinstIdsIsMutable() {
      if (!((bitField0_ & 0x00000020) != 0)) {
        probeFinstIds_ = new java.util.ArrayList<io.datafibre.fibre.proto.PUniqueId>(probeFinstIds_);
        bitField0_ |= 0x00000020;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.datafibre.fibre.proto.PUniqueId, io.datafibre.fibre.proto.PUniqueId.Builder, io.datafibre.fibre.proto.PUniqueIdOrBuilder> probeFinstIdsBuilder_;

    /**
     * <pre>
     * Multiple probe fragment instances maybe on a single host.
     * </pre>
     *
     * <code>repeated .starrocks.PUniqueId probe_finst_ids = 7;</code>
     */
    public java.util.List<io.datafibre.fibre.proto.PUniqueId> getProbeFinstIdsList() {
      if (probeFinstIdsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(probeFinstIds_);
      } else {
        return probeFinstIdsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Multiple probe fragment instances maybe on a single host.
     * </pre>
     *
     * <code>repeated .starrocks.PUniqueId probe_finst_ids = 7;</code>
     */
    public int getProbeFinstIdsCount() {
      if (probeFinstIdsBuilder_ == null) {
        return probeFinstIds_.size();
      } else {
        return probeFinstIdsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Multiple probe fragment instances maybe on a single host.
     * </pre>
     *
     * <code>repeated .starrocks.PUniqueId probe_finst_ids = 7;</code>
     */
    public io.datafibre.fibre.proto.PUniqueId getProbeFinstIds(int index) {
      if (probeFinstIdsBuilder_ == null) {
        return probeFinstIds_.get(index);
      } else {
        return probeFinstIdsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Multiple probe fragment instances maybe on a single host.
     * </pre>
     *
     * <code>repeated .starrocks.PUniqueId probe_finst_ids = 7;</code>
     */
    public Builder setProbeFinstIds(
        int index, io.datafibre.fibre.proto.PUniqueId value) {
      if (probeFinstIdsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProbeFinstIdsIsMutable();
        probeFinstIds_.set(index, value);
        onChanged();
      } else {
        probeFinstIdsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Multiple probe fragment instances maybe on a single host.
     * </pre>
     *
     * <code>repeated .starrocks.PUniqueId probe_finst_ids = 7;</code>
     */
    public Builder setProbeFinstIds(
        int index, io.datafibre.fibre.proto.PUniqueId.Builder builderForValue) {
      if (probeFinstIdsBuilder_ == null) {
        ensureProbeFinstIdsIsMutable();
        probeFinstIds_.set(index, builderForValue.build());
        onChanged();
      } else {
        probeFinstIdsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Multiple probe fragment instances maybe on a single host.
     * </pre>
     *
     * <code>repeated .starrocks.PUniqueId probe_finst_ids = 7;</code>
     */
    public Builder addProbeFinstIds(io.datafibre.fibre.proto.PUniqueId value) {
      if (probeFinstIdsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProbeFinstIdsIsMutable();
        probeFinstIds_.add(value);
        onChanged();
      } else {
        probeFinstIdsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Multiple probe fragment instances maybe on a single host.
     * </pre>
     *
     * <code>repeated .starrocks.PUniqueId probe_finst_ids = 7;</code>
     */
    public Builder addProbeFinstIds(
        int index, io.datafibre.fibre.proto.PUniqueId value) {
      if (probeFinstIdsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProbeFinstIdsIsMutable();
        probeFinstIds_.add(index, value);
        onChanged();
      } else {
        probeFinstIdsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Multiple probe fragment instances maybe on a single host.
     * </pre>
     *
     * <code>repeated .starrocks.PUniqueId probe_finst_ids = 7;</code>
     */
    public Builder addProbeFinstIds(
        io.datafibre.fibre.proto.PUniqueId.Builder builderForValue) {
      if (probeFinstIdsBuilder_ == null) {
        ensureProbeFinstIdsIsMutable();
        probeFinstIds_.add(builderForValue.build());
        onChanged();
      } else {
        probeFinstIdsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Multiple probe fragment instances maybe on a single host.
     * </pre>
     *
     * <code>repeated .starrocks.PUniqueId probe_finst_ids = 7;</code>
     */
    public Builder addProbeFinstIds(
        int index, io.datafibre.fibre.proto.PUniqueId.Builder builderForValue) {
      if (probeFinstIdsBuilder_ == null) {
        ensureProbeFinstIdsIsMutable();
        probeFinstIds_.add(index, builderForValue.build());
        onChanged();
      } else {
        probeFinstIdsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Multiple probe fragment instances maybe on a single host.
     * </pre>
     *
     * <code>repeated .starrocks.PUniqueId probe_finst_ids = 7;</code>
     */
    public Builder addAllProbeFinstIds(
        java.lang.Iterable<? extends io.datafibre.fibre.proto.PUniqueId> values) {
      if (probeFinstIdsBuilder_ == null) {
        ensureProbeFinstIdsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, probeFinstIds_);
        onChanged();
      } else {
        probeFinstIdsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Multiple probe fragment instances maybe on a single host.
     * </pre>
     *
     * <code>repeated .starrocks.PUniqueId probe_finst_ids = 7;</code>
     */
    public Builder clearProbeFinstIds() {
      if (probeFinstIdsBuilder_ == null) {
        probeFinstIds_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
      } else {
        probeFinstIdsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Multiple probe fragment instances maybe on a single host.
     * </pre>
     *
     * <code>repeated .starrocks.PUniqueId probe_finst_ids = 7;</code>
     */
    public Builder removeProbeFinstIds(int index) {
      if (probeFinstIdsBuilder_ == null) {
        ensureProbeFinstIdsIsMutable();
        probeFinstIds_.remove(index);
        onChanged();
      } else {
        probeFinstIdsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Multiple probe fragment instances maybe on a single host.
     * </pre>
     *
     * <code>repeated .starrocks.PUniqueId probe_finst_ids = 7;</code>
     */
    public io.datafibre.fibre.proto.PUniqueId.Builder getProbeFinstIdsBuilder(
        int index) {
      return getProbeFinstIdsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Multiple probe fragment instances maybe on a single host.
     * </pre>
     *
     * <code>repeated .starrocks.PUniqueId probe_finst_ids = 7;</code>
     */
    public io.datafibre.fibre.proto.PUniqueIdOrBuilder getProbeFinstIdsOrBuilder(
        int index) {
      if (probeFinstIdsBuilder_ == null) {
        return probeFinstIds_.get(index);  } else {
        return probeFinstIdsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Multiple probe fragment instances maybe on a single host.
     * </pre>
     *
     * <code>repeated .starrocks.PUniqueId probe_finst_ids = 7;</code>
     */
    public java.util.List<? extends io.datafibre.fibre.proto.PUniqueIdOrBuilder>
         getProbeFinstIdsOrBuilderList() {
      if (probeFinstIdsBuilder_ != null) {
        return probeFinstIdsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(probeFinstIds_);
      }
    }
    /**
     * <pre>
     * Multiple probe fragment instances maybe on a single host.
     * </pre>
     *
     * <code>repeated .starrocks.PUniqueId probe_finst_ids = 7;</code>
     */
    public io.datafibre.fibre.proto.PUniqueId.Builder addProbeFinstIdsBuilder() {
      return getProbeFinstIdsFieldBuilder().addBuilder(
          io.datafibre.fibre.proto.PUniqueId.getDefaultInstance());
    }
    /**
     * <pre>
     * Multiple probe fragment instances maybe on a single host.
     * </pre>
     *
     * <code>repeated .starrocks.PUniqueId probe_finst_ids = 7;</code>
     */
    public io.datafibre.fibre.proto.PUniqueId.Builder addProbeFinstIdsBuilder(
        int index) {
      return getProbeFinstIdsFieldBuilder().addBuilder(
          index, io.datafibre.fibre.proto.PUniqueId.getDefaultInstance());
    }
    /**
     * <pre>
     * Multiple probe fragment instances maybe on a single host.
     * </pre>
     *
     * <code>repeated .starrocks.PUniqueId probe_finst_ids = 7;</code>
     */
    public java.util.List<io.datafibre.fibre.proto.PUniqueId.Builder>
         getProbeFinstIdsBuilderList() {
      return getProbeFinstIdsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.datafibre.fibre.proto.PUniqueId, io.datafibre.fibre.proto.PUniqueId.Builder, io.datafibre.fibre.proto.PUniqueIdOrBuilder>
        getProbeFinstIdsFieldBuilder() {
      if (probeFinstIdsBuilder_ == null) {
        probeFinstIdsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.datafibre.fibre.proto.PUniqueId, io.datafibre.fibre.proto.PUniqueId.Builder, io.datafibre.fibre.proto.PUniqueIdOrBuilder>(
                probeFinstIds_,
                ((bitField0_ & 0x00000020) != 0),
                getParentForChildren(),
                isClean());
        probeFinstIds_ = null;
      }
      return probeFinstIdsBuilder_;
    }

    private int buildBeNumber_ ;
    /**
     * <code>optional int32 build_be_number = 8;</code>
     * @return Whether the buildBeNumber field is set.
     */
    @java.lang.Override
    public boolean hasBuildBeNumber() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional int32 build_be_number = 8;</code>
     * @return The buildBeNumber.
     */
    @java.lang.Override
    public int getBuildBeNumber() {
      return buildBeNumber_;
    }
    /**
     * <code>optional int32 build_be_number = 8;</code>
     * @param value The buildBeNumber to set.
     * @return This builder for chaining.
     */
    public Builder setBuildBeNumber(int value) {
      bitField0_ |= 0x00000040;
      buildBeNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 build_be_number = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearBuildBeNumber() {
      bitField0_ = (bitField0_ & ~0x00000040);
      buildBeNumber_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<io.datafibre.fibre.proto.PTransmitRuntimeFilterForwardTarget> forwardTargets_ =
      java.util.Collections.emptyList();
    private void ensureForwardTargetsIsMutable() {
      if (!((bitField0_ & 0x00000080) != 0)) {
        forwardTargets_ = new java.util.ArrayList<io.datafibre.fibre.proto.PTransmitRuntimeFilterForwardTarget>(forwardTargets_);
        bitField0_ |= 0x00000080;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.datafibre.fibre.proto.PTransmitRuntimeFilterForwardTarget, io.datafibre.fibre.proto.PTransmitRuntimeFilterForwardTarget.Builder, io.datafibre.fibre.proto.PTransmitRuntimeFilterForwardTargetOrBuilder> forwardTargetsBuilder_;

    /**
     * <code>repeated .starrocks.PTransmitRuntimeFilterForwardTarget forward_targets = 9;</code>
     */
    public java.util.List<io.datafibre.fibre.proto.PTransmitRuntimeFilterForwardTarget> getForwardTargetsList() {
      if (forwardTargetsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(forwardTargets_);
      } else {
        return forwardTargetsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .starrocks.PTransmitRuntimeFilterForwardTarget forward_targets = 9;</code>
     */
    public int getForwardTargetsCount() {
      if (forwardTargetsBuilder_ == null) {
        return forwardTargets_.size();
      } else {
        return forwardTargetsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .starrocks.PTransmitRuntimeFilterForwardTarget forward_targets = 9;</code>
     */
    public io.datafibre.fibre.proto.PTransmitRuntimeFilterForwardTarget getForwardTargets(int index) {
      if (forwardTargetsBuilder_ == null) {
        return forwardTargets_.get(index);
      } else {
        return forwardTargetsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .starrocks.PTransmitRuntimeFilterForwardTarget forward_targets = 9;</code>
     */
    public Builder setForwardTargets(
        int index, io.datafibre.fibre.proto.PTransmitRuntimeFilterForwardTarget value) {
      if (forwardTargetsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureForwardTargetsIsMutable();
        forwardTargets_.set(index, value);
        onChanged();
      } else {
        forwardTargetsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .starrocks.PTransmitRuntimeFilterForwardTarget forward_targets = 9;</code>
     */
    public Builder setForwardTargets(
        int index, io.datafibre.fibre.proto.PTransmitRuntimeFilterForwardTarget.Builder builderForValue) {
      if (forwardTargetsBuilder_ == null) {
        ensureForwardTargetsIsMutable();
        forwardTargets_.set(index, builderForValue.build());
        onChanged();
      } else {
        forwardTargetsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .starrocks.PTransmitRuntimeFilterForwardTarget forward_targets = 9;</code>
     */
    public Builder addForwardTargets(io.datafibre.fibre.proto.PTransmitRuntimeFilterForwardTarget value) {
      if (forwardTargetsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureForwardTargetsIsMutable();
        forwardTargets_.add(value);
        onChanged();
      } else {
        forwardTargetsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .starrocks.PTransmitRuntimeFilterForwardTarget forward_targets = 9;</code>
     */
    public Builder addForwardTargets(
        int index, io.datafibre.fibre.proto.PTransmitRuntimeFilterForwardTarget value) {
      if (forwardTargetsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureForwardTargetsIsMutable();
        forwardTargets_.add(index, value);
        onChanged();
      } else {
        forwardTargetsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .starrocks.PTransmitRuntimeFilterForwardTarget forward_targets = 9;</code>
     */
    public Builder addForwardTargets(
        io.datafibre.fibre.proto.PTransmitRuntimeFilterForwardTarget.Builder builderForValue) {
      if (forwardTargetsBuilder_ == null) {
        ensureForwardTargetsIsMutable();
        forwardTargets_.add(builderForValue.build());
        onChanged();
      } else {
        forwardTargetsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .starrocks.PTransmitRuntimeFilterForwardTarget forward_targets = 9;</code>
     */
    public Builder addForwardTargets(
        int index, io.datafibre.fibre.proto.PTransmitRuntimeFilterForwardTarget.Builder builderForValue) {
      if (forwardTargetsBuilder_ == null) {
        ensureForwardTargetsIsMutable();
        forwardTargets_.add(index, builderForValue.build());
        onChanged();
      } else {
        forwardTargetsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .starrocks.PTransmitRuntimeFilterForwardTarget forward_targets = 9;</code>
     */
    public Builder addAllForwardTargets(
        java.lang.Iterable<? extends io.datafibre.fibre.proto.PTransmitRuntimeFilterForwardTarget> values) {
      if (forwardTargetsBuilder_ == null) {
        ensureForwardTargetsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, forwardTargets_);
        onChanged();
      } else {
        forwardTargetsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .starrocks.PTransmitRuntimeFilterForwardTarget forward_targets = 9;</code>
     */
    public Builder clearForwardTargets() {
      if (forwardTargetsBuilder_ == null) {
        forwardTargets_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
      } else {
        forwardTargetsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .starrocks.PTransmitRuntimeFilterForwardTarget forward_targets = 9;</code>
     */
    public Builder removeForwardTargets(int index) {
      if (forwardTargetsBuilder_ == null) {
        ensureForwardTargetsIsMutable();
        forwardTargets_.remove(index);
        onChanged();
      } else {
        forwardTargetsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .starrocks.PTransmitRuntimeFilterForwardTarget forward_targets = 9;</code>
     */
    public io.datafibre.fibre.proto.PTransmitRuntimeFilterForwardTarget.Builder getForwardTargetsBuilder(
        int index) {
      return getForwardTargetsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .starrocks.PTransmitRuntimeFilterForwardTarget forward_targets = 9;</code>
     */
    public io.datafibre.fibre.proto.PTransmitRuntimeFilterForwardTargetOrBuilder getForwardTargetsOrBuilder(
        int index) {
      if (forwardTargetsBuilder_ == null) {
        return forwardTargets_.get(index);  } else {
        return forwardTargetsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .starrocks.PTransmitRuntimeFilterForwardTarget forward_targets = 9;</code>
     */
    public java.util.List<? extends io.datafibre.fibre.proto.PTransmitRuntimeFilterForwardTargetOrBuilder>
         getForwardTargetsOrBuilderList() {
      if (forwardTargetsBuilder_ != null) {
        return forwardTargetsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(forwardTargets_);
      }
    }
    /**
     * <code>repeated .starrocks.PTransmitRuntimeFilterForwardTarget forward_targets = 9;</code>
     */
    public io.datafibre.fibre.proto.PTransmitRuntimeFilterForwardTarget.Builder addForwardTargetsBuilder() {
      return getForwardTargetsFieldBuilder().addBuilder(
          io.datafibre.fibre.proto.PTransmitRuntimeFilterForwardTarget.getDefaultInstance());
    }
    /**
     * <code>repeated .starrocks.PTransmitRuntimeFilterForwardTarget forward_targets = 9;</code>
     */
    public io.datafibre.fibre.proto.PTransmitRuntimeFilterForwardTarget.Builder addForwardTargetsBuilder(
        int index) {
      return getForwardTargetsFieldBuilder().addBuilder(
          index, io.datafibre.fibre.proto.PTransmitRuntimeFilterForwardTarget.getDefaultInstance());
    }
    /**
     * <code>repeated .starrocks.PTransmitRuntimeFilterForwardTarget forward_targets = 9;</code>
     */
    public java.util.List<io.datafibre.fibre.proto.PTransmitRuntimeFilterForwardTarget.Builder>
         getForwardTargetsBuilderList() {
      return getForwardTargetsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.datafibre.fibre.proto.PTransmitRuntimeFilterForwardTarget, io.datafibre.fibre.proto.PTransmitRuntimeFilterForwardTarget.Builder, io.datafibre.fibre.proto.PTransmitRuntimeFilterForwardTargetOrBuilder>
        getForwardTargetsFieldBuilder() {
      if (forwardTargetsBuilder_ == null) {
        forwardTargetsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.datafibre.fibre.proto.PTransmitRuntimeFilterForwardTarget, io.datafibre.fibre.proto.PTransmitRuntimeFilterForwardTarget.Builder, io.datafibre.fibre.proto.PTransmitRuntimeFilterForwardTargetOrBuilder>(
                forwardTargets_,
                ((bitField0_ & 0x00000080) != 0),
                getParentForChildren(),
                isClean());
        forwardTargets_ = null;
      }
      return forwardTargetsBuilder_;
    }

    private long broadcastTimestamp_ ;
    /**
     * <pre>
     * When merge node starts to broadcast this rf(millseconds since unix epoch).
     * </pre>
     *
     * <code>optional int64 broadcast_timestamp = 10;</code>
     * @return Whether the broadcastTimestamp field is set.
     */
    @java.lang.Override
    public boolean hasBroadcastTimestamp() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <pre>
     * When merge node starts to broadcast this rf(millseconds since unix epoch).
     * </pre>
     *
     * <code>optional int64 broadcast_timestamp = 10;</code>
     * @return The broadcastTimestamp.
     */
    @java.lang.Override
    public long getBroadcastTimestamp() {
      return broadcastTimestamp_;
    }
    /**
     * <pre>
     * When merge node starts to broadcast this rf(millseconds since unix epoch).
     * </pre>
     *
     * <code>optional int64 broadcast_timestamp = 10;</code>
     * @param value The broadcastTimestamp to set.
     * @return This builder for chaining.
     */
    public Builder setBroadcastTimestamp(long value) {
      bitField0_ |= 0x00000100;
      broadcastTimestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * When merge node starts to broadcast this rf(millseconds since unix epoch).
     * </pre>
     *
     * <code>optional int64 broadcast_timestamp = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearBroadcastTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000100);
      broadcastTimestamp_ = 0L;
      onChanged();
      return this;
    }

    private boolean isPipeline_ ;
    /**
     * <code>optional bool is_pipeline = 11;</code>
     * @return Whether the isPipeline field is set.
     */
    @java.lang.Override
    public boolean hasIsPipeline() {
      return ((bitField0_ & 0x00000200) != 0);
    }
    /**
     * <code>optional bool is_pipeline = 11;</code>
     * @return The isPipeline.
     */
    @java.lang.Override
    public boolean getIsPipeline() {
      return isPipeline_;
    }
    /**
     * <code>optional bool is_pipeline = 11;</code>
     * @param value The isPipeline to set.
     * @return This builder for chaining.
     */
    public Builder setIsPipeline(boolean value) {
      bitField0_ |= 0x00000200;
      isPipeline_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool is_pipeline = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsPipeline() {
      bitField0_ = (bitField0_ & ~0x00000200);
      isPipeline_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:starrocks.PTransmitRuntimeFilterParams)
  }

  // @@protoc_insertion_point(class_scope:starrocks.PTransmitRuntimeFilterParams)
  private static final io.datafibre.fibre.proto.PTransmitRuntimeFilterParams DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.datafibre.fibre.proto.PTransmitRuntimeFilterParams();
  }

  public static io.datafibre.fibre.proto.PTransmitRuntimeFilterParams getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<PTransmitRuntimeFilterParams>
      PARSER = new com.google.protobuf.AbstractParser<PTransmitRuntimeFilterParams>() {
    @java.lang.Override
    public PTransmitRuntimeFilterParams parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PTransmitRuntimeFilterParams> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PTransmitRuntimeFilterParams> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.datafibre.fibre.proto.PTransmitRuntimeFilterParams getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

