// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: olap_file.proto

package io.datafibre.fibre.proto;

public interface TabletMetaPBOrBuilder extends
    // @@protoc_insertion_point(interface_extends:starrocks.TabletMetaPB)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * ?
   * </pre>
   *
   * <code>optional int64 table_id = 1;</code>
   * @return Whether the tableId field is set.
   */
  boolean hasTableId();
  /**
   * <pre>
   * ?
   * </pre>
   *
   * <code>optional int64 table_id = 1;</code>
   * @return The tableId.
   */
  long getTableId();

  /**
   * <pre>
   * ?
   * </pre>
   *
   * <code>optional int64 partition_id = 2;</code>
   * @return Whether the partitionId field is set.
   */
  boolean hasPartitionId();
  /**
   * <pre>
   * ?
   * </pre>
   *
   * <code>optional int64 partition_id = 2;</code>
   * @return The partitionId.
   */
  long getPartitionId();

  /**
   * <pre>
   * OlapHeaderMessage.tablet_id
   * </pre>
   *
   * <code>optional int64 tablet_id = 3;</code>
   * @return Whether the tabletId field is set.
   */
  boolean hasTabletId();
  /**
   * <pre>
   * OlapHeaderMessage.tablet_id
   * </pre>
   *
   * <code>optional int64 tablet_id = 3;</code>
   * @return The tabletId.
   */
  long getTabletId();

  /**
   * <pre>
   * OlapHeaderMessage.schema_hash
   * </pre>
   *
   * <code>optional int32 schema_hash = 4;</code>
   * @return Whether the schemaHash field is set.
   */
  boolean hasSchemaHash();
  /**
   * <pre>
   * OlapHeaderMessage.schema_hash
   * </pre>
   *
   * <code>optional int32 schema_hash = 4;</code>
   * @return The schemaHash.
   */
  int getSchemaHash();

  /**
   * <pre>
   * OlapHeaderMessage.shard
   * </pre>
   *
   * <code>optional int32 shard_id = 5;</code>
   * @return Whether the shardId field is set.
   */
  boolean hasShardId();
  /**
   * <pre>
   * OlapHeaderMessage.shard
   * </pre>
   *
   * <code>optional int32 shard_id = 5;</code>
   * @return The shardId.
   */
  int getShardId();

  /**
   * <pre>
   * OlapHeaderMessage.creation_time
   * </pre>
   *
   * <code>optional int64 creation_time = 6;</code>
   * @return Whether the creationTime field is set.
   */
  boolean hasCreationTime();
  /**
   * <pre>
   * OlapHeaderMessage.creation_time
   * </pre>
   *
   * <code>optional int64 creation_time = 6;</code>
   * @return The creationTime.
   */
  long getCreationTime();

  /**
   * <pre>
   * OlapHeaderMessage.cumulative_layer_point
   * </pre>
   *
   * <code>optional int64 cumulative_layer_point = 7;</code>
   * @return Whether the cumulativeLayerPoint field is set.
   */
  boolean hasCumulativeLayerPoint();
  /**
   * <pre>
   * OlapHeaderMessage.cumulative_layer_point
   * </pre>
   *
   * <code>optional int64 cumulative_layer_point = 7;</code>
   * @return The cumulativeLayerPoint.
   */
  long getCumulativeLayerPoint();

  /**
   * <code>optional .starrocks.TabletStatePB tablet_state = 8;</code>
   * @return Whether the tabletState field is set.
   */
  boolean hasTabletState();
  /**
   * <code>optional .starrocks.TabletStatePB tablet_state = 8;</code>
   * @return The tabletState.
   */
  io.datafibre.fibre.proto.TabletStatePB getTabletState();

  /**
   * <code>optional .starrocks.TabletSchemaPB schema = 9;</code>
   * @return Whether the schema field is set.
   */
  boolean hasSchema();
  /**
   * <code>optional .starrocks.TabletSchemaPB schema = 9;</code>
   * @return The schema.
   */
  io.datafibre.fibre.proto.TabletSchemaPB getSchema();
  /**
   * <code>optional .starrocks.TabletSchemaPB schema = 9;</code>
   */
  io.datafibre.fibre.proto.TabletSchemaPBOrBuilder getSchemaOrBuilder();

  /**
   * <code>repeated .starrocks.RowsetMetaPB rs_metas = 10;</code>
   */
  java.util.List<io.datafibre.fibre.proto.RowsetMetaPB>
      getRsMetasList();
  /**
   * <code>repeated .starrocks.RowsetMetaPB rs_metas = 10;</code>
   */
  io.datafibre.fibre.proto.RowsetMetaPB getRsMetas(int index);
  /**
   * <code>repeated .starrocks.RowsetMetaPB rs_metas = 10;</code>
   */
  int getRsMetasCount();
  /**
   * <code>repeated .starrocks.RowsetMetaPB rs_metas = 10;</code>
   */
  java.util.List<? extends io.datafibre.fibre.proto.RowsetMetaPBOrBuilder>
      getRsMetasOrBuilderList();
  /**
   * <code>repeated .starrocks.RowsetMetaPB rs_metas = 10;</code>
   */
  io.datafibre.fibre.proto.RowsetMetaPBOrBuilder getRsMetasOrBuilder(
      int index);

  /**
   * <code>repeated .starrocks.RowsetMetaPB inc_rs_metas = 11;</code>
   */
  java.util.List<io.datafibre.fibre.proto.RowsetMetaPB>
      getIncRsMetasList();
  /**
   * <code>repeated .starrocks.RowsetMetaPB inc_rs_metas = 11;</code>
   */
  io.datafibre.fibre.proto.RowsetMetaPB getIncRsMetas(int index);
  /**
   * <code>repeated .starrocks.RowsetMetaPB inc_rs_metas = 11;</code>
   */
  int getIncRsMetasCount();
  /**
   * <code>repeated .starrocks.RowsetMetaPB inc_rs_metas = 11;</code>
   */
  java.util.List<? extends io.datafibre.fibre.proto.RowsetMetaPBOrBuilder>
      getIncRsMetasOrBuilderList();
  /**
   * <code>repeated .starrocks.RowsetMetaPB inc_rs_metas = 11;</code>
   */
  io.datafibre.fibre.proto.RowsetMetaPBOrBuilder getIncRsMetasOrBuilder(
      int index);

  /**
   * <code>optional .starrocks.AlterTabletPB alter_task = 12 [deprecated = true];</code>
   * @deprecated starrocks.TabletMetaPB.alter_task is deprecated.
   *     See olap_file.proto;l=280
   * @return Whether the alterTask field is set.
   */
  @java.lang.Deprecated boolean hasAlterTask();
  /**
   * <code>optional .starrocks.AlterTabletPB alter_task = 12 [deprecated = true];</code>
   * @deprecated starrocks.TabletMetaPB.alter_task is deprecated.
   *     See olap_file.proto;l=280
   * @return The alterTask.
   */
  @java.lang.Deprecated io.datafibre.fibre.proto.AlterTabletPB getAlterTask();
  /**
   * <code>optional .starrocks.AlterTabletPB alter_task = 12 [deprecated = true];</code>
   */
  @java.lang.Deprecated io.datafibre.fibre.proto.AlterTabletPBOrBuilder getAlterTaskOrBuilder();

  /**
   * <pre>
   * if true, this tablet will not do compaction,
   * and does not create init version
   * </pre>
   *
   * <code>optional bool in_restore_mode = 13 [default = false];</code>
   * @return Whether the inRestoreMode field is set.
   */
  boolean hasInRestoreMode();
  /**
   * <pre>
   * if true, this tablet will not do compaction,
   * and does not create init version
   * </pre>
   *
   * <code>optional bool in_restore_mode = 13 [default = false];</code>
   * @return The inRestoreMode.
   */
  boolean getInRestoreMode();

  /**
   * <pre>
   * a uniqued id to identified tablet with same tablet_id and schema hash
   * </pre>
   *
   * <code>optional .starrocks.PUniqueId tablet_uid = 14;</code>
   * @return Whether the tabletUid field is set.
   */
  boolean hasTabletUid();
  /**
   * <pre>
   * a uniqued id to identified tablet with same tablet_id and schema hash
   * </pre>
   *
   * <code>optional .starrocks.PUniqueId tablet_uid = 14;</code>
   * @return The tabletUid.
   */
  io.datafibre.fibre.proto.PUniqueId getTabletUid();
  /**
   * <pre>
   * a uniqued id to identified tablet with same tablet_id and schema hash
   * </pre>
   *
   * <code>optional .starrocks.PUniqueId tablet_uid = 14;</code>
   */
  io.datafibre.fibre.proto.PUniqueIdOrBuilder getTabletUidOrBuilder();

  /**
   * <code>optional int64 end_rowset_id = 15;</code>
   * @return Whether the endRowsetId field is set.
   */
  boolean hasEndRowsetId();
  /**
   * <code>optional int64 end_rowset_id = 15;</code>
   * @return The endRowsetId.
   */
  long getEndRowsetId();

  /**
   * <code>optional .starrocks.RowsetTypePB preferred_rowset_type = 16 [default = BETA_ROWSET, deprecated = true];</code>
   * @deprecated starrocks.TabletMetaPB.preferred_rowset_type is deprecated.
   *     See olap_file.proto;l=287
   * @return Whether the preferredRowsetType field is set.
   */
  @java.lang.Deprecated boolean hasPreferredRowsetType();
  /**
   * <code>optional .starrocks.RowsetTypePB preferred_rowset_type = 16 [default = BETA_ROWSET, deprecated = true];</code>
   * @deprecated starrocks.TabletMetaPB.preferred_rowset_type is deprecated.
   *     See olap_file.proto;l=287
   * @return The preferredRowsetType.
   */
  @java.lang.Deprecated io.datafibre.fibre.proto.RowsetTypePB getPreferredRowsetType();

  /**
   * <code>optional .starrocks.TabletTypePB tablet_type = 17;</code>
   * @return Whether the tabletType field is set.
   */
  boolean hasTabletType();
  /**
   * <code>optional .starrocks.TabletTypePB tablet_type = 17;</code>
   * @return The tabletType.
   */
  io.datafibre.fibre.proto.TabletTypePB getTabletType();

  /**
   * <pre>
   * used for new updatable tablet
   * </pre>
   *
   * <code>optional .starrocks.TabletUpdatesPB updates = 50;</code>
   * @return Whether the updates field is set.
   */
  boolean hasUpdates();
  /**
   * <pre>
   * used for new updatable tablet
   * </pre>
   *
   * <code>optional .starrocks.TabletUpdatesPB updates = 50;</code>
   * @return The updates.
   */
  io.datafibre.fibre.proto.TabletUpdatesPB getUpdates();
  /**
   * <pre>
   * used for new updatable tablet
   * </pre>
   *
   * <code>optional .starrocks.TabletUpdatesPB updates = 50;</code>
   */
  io.datafibre.fibre.proto.TabletUpdatesPBOrBuilder getUpdatesOrBuilder();

  /**
   * <pre>
   * used for persistent index in primary index
   * </pre>
   *
   * <code>optional bool enable_persistent_index = 51 [default = false];</code>
   * @return Whether the enablePersistentIndex field is set.
   */
  boolean hasEnablePersistentIndex();
  /**
   * <pre>
   * used for persistent index in primary index
   * </pre>
   *
   * <code>optional bool enable_persistent_index = 51 [default = false];</code>
   * @return The enablePersistentIndex.
   */
  boolean getEnablePersistentIndex();

  /**
   * <code>optional .starrocks.BinlogConfigPB binlog_config = 52;</code>
   * @return Whether the binlogConfig field is set.
   */
  boolean hasBinlogConfig();
  /**
   * <code>optional .starrocks.BinlogConfigPB binlog_config = 52;</code>
   * @return The binlogConfig.
   */
  io.datafibre.fibre.proto.BinlogConfigPB getBinlogConfig();
  /**
   * <code>optional .starrocks.BinlogConfigPB binlog_config = 52;</code>
   */
  io.datafibre.fibre.proto.BinlogConfigPBOrBuilder getBinlogConfigOrBuilder();

  /**
   * <code>optional .starrocks.BinlogLsnPB binlog_min_lsn = 53;</code>
   * @return Whether the binlogMinLsn field is set.
   */
  boolean hasBinlogMinLsn();
  /**
   * <code>optional .starrocks.BinlogLsnPB binlog_min_lsn = 53;</code>
   * @return The binlogMinLsn.
   */
  io.datafibre.fibre.proto.BinlogLsnPB getBinlogMinLsn();
  /**
   * <code>optional .starrocks.BinlogLsnPB binlog_min_lsn = 53;</code>
   */
  io.datafibre.fibre.proto.BinlogLsnPBOrBuilder getBinlogMinLsnOrBuilder();

  /**
   * <pre>
   * storage layout type: column[default]|column_with_row|row
   * </pre>
   *
   * <code>optional string storage_type = 54;</code>
   * @return Whether the storageType field is set.
   */
  boolean hasStorageType();
  /**
   * <pre>
   * storage layout type: column[default]|column_with_row|row
   * </pre>
   *
   * <code>optional string storage_type = 54;</code>
   * @return The storageType.
   */
  java.lang.String getStorageType();
  /**
   * <pre>
   * storage layout type: column[default]|column_with_row|row
   * </pre>
   *
   * <code>optional string storage_type = 54;</code>
   * @return The bytes for storageType.
   */
  com.google.protobuf.ByteString
      getStorageTypeBytes();

  /**
   * <code>optional bool enable_shortcut_compaction = 60 [default = true];</code>
   * @return Whether the enableShortcutCompaction field is set.
   */
  boolean hasEnableShortcutCompaction();
  /**
   * <code>optional bool enable_shortcut_compaction = 60 [default = true];</code>
   * @return The enableShortcutCompaction.
   */
  boolean getEnableShortcutCompaction();

  /**
   * <code>optional int32 primary_index_cache_expire_sec = 61 [default = 0];</code>
   * @return Whether the primaryIndexCacheExpireSec field is set.
   */
  boolean hasPrimaryIndexCacheExpireSec();
  /**
   * <code>optional int32 primary_index_cache_expire_sec = 61 [default = 0];</code>
   * @return The primaryIndexCacheExpireSec.
   */
  int getPrimaryIndexCacheExpireSec();

  /**
   * <pre>
   * If the tablet is replicated from another cluster, the source_schema saved the schema in the cluster
   * </pre>
   *
   * <code>optional .starrocks.TabletSchemaPB source_schema = 70;</code>
   * @return Whether the sourceSchema field is set.
   */
  boolean hasSourceSchema();
  /**
   * <pre>
   * If the tablet is replicated from another cluster, the source_schema saved the schema in the cluster
   * </pre>
   *
   * <code>optional .starrocks.TabletSchemaPB source_schema = 70;</code>
   * @return The sourceSchema.
   */
  io.datafibre.fibre.proto.TabletSchemaPB getSourceSchema();
  /**
   * <pre>
   * If the tablet is replicated from another cluster, the source_schema saved the schema in the cluster
   * </pre>
   *
   * <code>optional .starrocks.TabletSchemaPB source_schema = 70;</code>
   */
  io.datafibre.fibre.proto.TabletSchemaPBOrBuilder getSourceSchemaOrBuilder();
}
