/**
 * Autogenerated by Thrift Compiler (0.19.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.starrocks.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.19.0)", date = "2024-02-22")
public class TGetTabletScheduleResponse implements org.apache.thrift.TBase<TGetTabletScheduleResponse, TGetTabletScheduleResponse._Fields>, java.io.Serializable, Cloneable, Comparable<TGetTabletScheduleResponse> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TGetTabletScheduleResponse");

  private static final org.apache.thrift.protocol.TField TABLET_SCHEDULES_FIELD_DESC = new org.apache.thrift.protocol.TField("tablet_schedules", org.apache.thrift.protocol.TType.LIST, (short)1);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new TGetTabletScheduleResponseStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new TGetTabletScheduleResponseTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.util.List<TTabletSchedule> tablet_schedules; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    TABLET_SCHEDULES((short)1, "tablet_schedules");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // TABLET_SCHEDULES
          return TABLET_SCHEDULES;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final _Fields optionals[] = {_Fields.TABLET_SCHEDULES};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.TABLET_SCHEDULES, new org.apache.thrift.meta_data.FieldMetaData("tablet_schedules", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TTabletSchedule.class))));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TGetTabletScheduleResponse.class, metaDataMap);
  }

  public TGetTabletScheduleResponse() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TGetTabletScheduleResponse(TGetTabletScheduleResponse other) {
    if (other.isSetTablet_schedules()) {
      java.util.List<TTabletSchedule> __this__tablet_schedules = new java.util.ArrayList<TTabletSchedule>(other.tablet_schedules.size());
      for (TTabletSchedule other_element : other.tablet_schedules) {
        __this__tablet_schedules.add(new TTabletSchedule(other_element));
      }
      this.tablet_schedules = __this__tablet_schedules;
    }
  }

  @Override
  public TGetTabletScheduleResponse deepCopy() {
    return new TGetTabletScheduleResponse(this);
  }

  @Override
  public void clear() {
    this.tablet_schedules = null;
  }

  public int getTablet_schedulesSize() {
    return (this.tablet_schedules == null) ? 0 : this.tablet_schedules.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<TTabletSchedule> getTablet_schedulesIterator() {
    return (this.tablet_schedules == null) ? null : this.tablet_schedules.iterator();
  }

  public void addToTablet_schedules(TTabletSchedule elem) {
    if (this.tablet_schedules == null) {
      this.tablet_schedules = new java.util.ArrayList<TTabletSchedule>();
    }
    this.tablet_schedules.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<TTabletSchedule> getTablet_schedules() {
    return this.tablet_schedules;
  }

  public TGetTabletScheduleResponse setTablet_schedules(@org.apache.thrift.annotation.Nullable java.util.List<TTabletSchedule> tablet_schedules) {
    this.tablet_schedules = tablet_schedules;
    return this;
  }

  public void unsetTablet_schedules() {
    this.tablet_schedules = null;
  }

  /** Returns true if field tablet_schedules is set (has been assigned a value) and false otherwise */
  public boolean isSetTablet_schedules() {
    return this.tablet_schedules != null;
  }

  public void setTablet_schedulesIsSet(boolean value) {
    if (!value) {
      this.tablet_schedules = null;
    }
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case TABLET_SCHEDULES:
      if (value == null) {
        unsetTablet_schedules();
      } else {
        setTablet_schedules((java.util.List<TTabletSchedule>)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case TABLET_SCHEDULES:
      return getTablet_schedules();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case TABLET_SCHEDULES:
      return isSetTablet_schedules();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof TGetTabletScheduleResponse)
      return this.equals((TGetTabletScheduleResponse)that);
    return false;
  }

  public boolean equals(TGetTabletScheduleResponse that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_tablet_schedules = true && this.isSetTablet_schedules();
    boolean that_present_tablet_schedules = true && that.isSetTablet_schedules();
    if (this_present_tablet_schedules || that_present_tablet_schedules) {
      if (!(this_present_tablet_schedules && that_present_tablet_schedules))
        return false;
      if (!this.tablet_schedules.equals(that.tablet_schedules))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetTablet_schedules()) ? 131071 : 524287);
    if (isSetTablet_schedules())
      hashCode = hashCode * 8191 + tablet_schedules.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(TGetTabletScheduleResponse other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetTablet_schedules(), other.isSetTablet_schedules());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTablet_schedules()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.tablet_schedules, other.tablet_schedules);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("TGetTabletScheduleResponse(");
    boolean first = true;

    if (isSetTablet_schedules()) {
      sb.append("tablet_schedules:");
      if (this.tablet_schedules == null) {
        sb.append("null");
      } else {
        sb.append(this.tablet_schedules);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TGetTabletScheduleResponseStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public TGetTabletScheduleResponseStandardScheme getScheme() {
      return new TGetTabletScheduleResponseStandardScheme();
    }
  }

  private static class TGetTabletScheduleResponseStandardScheme extends org.apache.thrift.scheme.StandardScheme<TGetTabletScheduleResponse> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, TGetTabletScheduleResponse struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // TABLET_SCHEDULES
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list694 = iprot.readListBegin();
                struct.tablet_schedules = new java.util.ArrayList<TTabletSchedule>(_list694.size);
                @org.apache.thrift.annotation.Nullable TTabletSchedule _elem695;
                for (int _i696 = 0; _i696 < _list694.size; ++_i696)
                {
                  _elem695 = new TTabletSchedule();
                  _elem695.read(iprot);
                  struct.tablet_schedules.add(_elem695);
                }
                iprot.readListEnd();
              }
              struct.setTablet_schedulesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, TGetTabletScheduleResponse struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.tablet_schedules != null) {
        if (struct.isSetTablet_schedules()) {
          oprot.writeFieldBegin(TABLET_SCHEDULES_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.tablet_schedules.size()));
            for (TTabletSchedule _iter697 : struct.tablet_schedules)
            {
              _iter697.write(oprot);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TGetTabletScheduleResponseTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public TGetTabletScheduleResponseTupleScheme getScheme() {
      return new TGetTabletScheduleResponseTupleScheme();
    }
  }

  private static class TGetTabletScheduleResponseTupleScheme extends org.apache.thrift.scheme.TupleScheme<TGetTabletScheduleResponse> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TGetTabletScheduleResponse struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetTablet_schedules()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetTablet_schedules()) {
        {
          oprot.writeI32(struct.tablet_schedules.size());
          for (TTabletSchedule _iter698 : struct.tablet_schedules)
          {
            _iter698.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TGetTabletScheduleResponse struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list699 = iprot.readListBegin(org.apache.thrift.protocol.TType.STRUCT);
          struct.tablet_schedules = new java.util.ArrayList<TTabletSchedule>(_list699.size);
          @org.apache.thrift.annotation.Nullable TTabletSchedule _elem700;
          for (int _i701 = 0; _i701 < _list699.size; ++_i701)
          {
            _elem700 = new TTabletSchedule();
            _elem700.read(iprot);
            struct.tablet_schedules.add(_elem700);
          }
        }
        struct.setTablet_schedulesIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

