/**
 * Autogenerated by Thrift Compiler (0.19.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package io.datafibre.fibre.thrift;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.19.0)", date = "2024-02-22")
public enum TRunMode implements org.apache.thrift.TEnum {
  SHARED_NOTHING(0),
  SHARED_DATA(1),
  HYBRID(2);

  private final int value;

  private TRunMode(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  @Override
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static TRunMode findByValue(int value) { 
    switch (value) {
      case 0:
        return SHARED_NOTHING;
      case 1:
        return SHARED_DATA;
      case 2:
        return HYBRID;
      default:
        return null;
    }
  }
}
